### ISSUE TITLE
What to do about this error 'tensorflow_text\python\ops\_regex_split_ops.so not found'?

### ISSUE THREAD

**Issue by HermanTam** [tensorflow/text#1001]
Traceback (most recent call last):
  File "C:\Users\user\Downloads\Test.py", line 10, in <module>
    import tensorflow_text as text
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow_text\__init__.py", line 21, in <module>
    from tensorflow_text.python import keras
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow_text\python\keras\__init__.py", line 21, in <module>
    from tensorflow_text.python.keras.layers import *
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow_text\python\keras\layers\__init__.py", line 22, in <module>
    from tensorflow_text.python.keras.layers.tokenization_layers import *
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow_text\python\keras\layers\tokenization_layers.py", line 25, in <module>
    from tensorflow_text.python.ops import unicode_script_tokenizer
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow_text\python\ops\__init__.py", line 25, in <module>
    from tensorflow_text.python.ops.bert_tokenizer import BertTokenizer
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow_text\python\ops\bert_tokenizer.py", line 28, in <module>
    from tensorflow_text.python.ops import regex_split_ops
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow_text\python\ops\regex_split_ops.py", line 23, in <module>
    gen_regex_split_ops = load_library.load_op_library(resource_loader.get_path_to_datafile('_regex_split_ops.so'))
  File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\tensorflow\python\framework\load_library.py", line 54, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow_text\python\ops\_regex_split_ops.so not found

tensorboard                  2.9.0
tensorboard-data-server      0.6.1
tensorboard-plugin-wit       1.8.1
tensorflow                   2.9.0
tensorflow-cpu               2.9.0
tensorflow-estimator         2.9.0
tensorflow-hub               0.12.0
tensorflow_intel             2.10.0
tensorflow-io-gcs-filesystem 0.26.0
tensorflow-text              2.9.0

Python 3.9.6
![image](https://user-images.githubusercontent.com/41150452/188927941-b918bfb8-0580-4a8b-8719-f8d927abaee6.png)

I am experiencing this problem when I try to do 'import tensorflow_text as text'. I tried to adjust the versions of tensorflow and tensorflow-text and it does not help. I couldn't find an answer. Does anyone have any idea about this issue? Any help is appreciated.

**Comment by broken** [comment]
It looks like it cannot find the kernels when loaded. If you look in that directory (C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow_text\python), do you see the shared object files (*.so)? Could TF Text have been installed into a different Python? Could it be a permission error for these?

**Comment by HermanTam** [comment]
Thank you very much for your reply. 


No, I don't see the object files (*.so) in that directory. 
![image](https://user-images.githubusercontent.com/41150452/189496450-9bdcc2d3-cc14-48d1-83cc-0e0707017cf0.png)

But there are *.so files in the ops folder.
![image](https://user-images.githubusercontent.com/41150452/189496508-20438619-5f5c-4e81-83d3-741d978d2525.png)


What is the way to determine if this is a permission error?


Do you mean if the TF text is installed into a different version of Python? Because I run the following command to install tensorflow-text:
py -3.9 -m pip install tensorflow-text

Result:
Requirement already satisfied: tensorflow-text in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (2.9.0)
Requirement already satisfied: tensorflow-hub>=0.8.0 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from tensorflow-text) (0.12.0)
Requirement already satisfied: tensorflow<2.10,>=2.9.0 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from tensorflow-text) (2.9.0)
Requirement already satisfied: typing-extensions>=3.6.6 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from tensorflow<2.10,>=2.9.0->tensorflow-text) (4.0.1)
Requirement already satisfied: astunparse>=1.6.0 in c:\users\user\appdata\roaming\python\python39\site-packages (from tensorflow<2.10,>=2.9.0->tensorflow-text) (1.6.3)
Requirement already satisfied: h5py>=2.9.0 in c:\users\user\appdata\roaming\python\python39\site-packages (from tensorflow<2.10,>=2.9.0->tensorflow-text) (3.7.0)
Requirement already satisfied: libclang>=13.0.0 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from tensorflow<2.10,>=2.9.0->tensorflow-text) (14.0.6)
Requirement already satisfied: packaging in c:\users\user\appdata\roaming\python\python39\site-packages (from tensorflow<2.10,>=2.9.0->tensorflow-text) (21.3)
Requirement already satisfied: tensorflow-estimator<2.10.0,>=2.9.0rc0 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from tensorflow<2.10,>=2.9.0->tensorflow-text) (2.9.0)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from tensorflow<2.10,>=2.9.0->tensorflow-text) (0.26.0)
Requirement already satisfied: numpy>=1.20 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from tensorflow<2.10,>=2.9.0->tensorflow-text) (1.22.0)
Requirement already satisfied: tensorboard<2.10,>=2.9 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from tensorflow<2.10,>=2.9.0->tensorflow-text) (2.9.0)
Requirement already satisfied: flatbuffers<2,>=1.12 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from tensorflow<2.10,>=2.9.0->tensorflow-text) (1.12)
Requirement already satisfied: gast<=0.4.0,>=0.2.1 in c:\users\user\appdata\roaming\python\python39\site-packages (from tensorflow<2.10,>=2.9.0->tensorflow-text) (0.4.0)
Requirement already satisfied: keras<2.10.0,>=2.9.0rc0 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from tensorflow<2.10,>=2.9.0->tensorflow-text) (2.9.0)
Requirement already satisfied: setuptools in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from tensorflow<2.10,>=2.9.0->tensorflow-text) (56.0.0)
Requirement already satisfied: six>=1.12.0 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from tensorflow<2.10,>=2.9.0->tensorflow-text) (1.16.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from tensorflow<2.10,>=2.9.0->tensorflow-text) (1.1.0)
Requirement already satisfied: keras-preprocessing>=1.1.1 in c:\users\user\appdata\roaming\python\python39\site-packages (from tensorflow<2.10,>=2.9.0->tensorflow-text) (1.1.2)
Requirement already satisfied: wrapt>=1.11.0 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from tensorflow<2.10,>=2.9.0->tensorflow-text) (1.14.1)
Requirement already satisfied: protobuf>=3.9.2 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from tensorflow<2.10,>=2.9.0->tensorflow-text) (3.19.4)
Requirement already satisfied: opt-einsum>=2.3.2 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from tensorflow<2.10,>=2.9.0->tensorflow-text) (3.3.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\users\user\appdata\roaming\python\python39\site-packages (from tensorflow<2.10,>=2.9.0->tensorflow-text) (1.48.1)
Requirement already satisfied: absl-py>=1.0.0 in c:\users\user\appdata\roaming\python\python39\site-packages (from tensorflow<2.10,>=2.9.0->tensorflow-text) (1.2.0)
Requirement already satisfied: google-pasta>=0.1.1 in c:\users\user\appdata\roaming\python\python39\site-packages (from tensorflow<2.10,>=2.9.0->tensorflow-text) (0.2.0)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from astunparse>=1.6.0->tensorflow<2.10,>=2.9.0->tensorflow-text) (0.37.1)
Requirement already satisfied: tensorboard-data-server<0.7.0,>=0.6.0 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from tensorboard<2.10,>=2.9->tensorflow<2.10,>=2.9.0->tensorflow-text) (0.6.1)
Requirement already satisfied: markdown>=2.6.8 in c:\users\user\appdata\roaming\python\python39\site-packages (from tensorboard<2.10,>=2.9->tensorflow<2.10,>=2.9.0->tensorflow-text) (3.4.1)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in c:\users\user\appdata\roaming\python\python39\site-packages (from tensorboard<2.10,>=2.9->tensorflow<2.10,>=2.9.0->tensorflow-text) (0.4.6)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from tensorboard<2.10,>=2.9->tensorflow<2.10,>=2.9.0->tensorflow-text) (2.26.0)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from tensorboard<2.10,>=2.9->tensorflow<2.10,>=2.9.0->tensorflow-text) (1.8.1)
Requirement already satisfied: google-auth<3,>=1.6.3 in c:\users\user\appdata\roaming\python\python39\site-packages (from tensorboard<2.10,>=2.9->tensorflow<2.10,>=2.9.0->tensorflow-text) (2.11.0)
Requirement already satisfied: werkzeug>=1.0.1 in c:\users\user\appdata\roaming\python\python39\site-packages (from tensorboard<2.10,>=2.9->tensorflow<2.10,>=2.9.0->tensorflow-text) (2.2.2)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in c:\users\user\appdata\roaming\python\python39\site-packages (from packaging->tensorflow<2.10,>=2.9.0->tensorflow-text) (3.0.6)
Requirement already satisfied: rsa<5,>=3.1.4 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard<2.10,>=2.9->tensorflow<2.10,>=2.9.0->tensorflow-text) (4.9)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in c:\users\user\appdata\roaming\python\python39\site-packages (from google-auth<3,>=1.6.3->tensorboard<2.10,>=2.9->tensorflow<2.10,>=2.9.0->tensorflow-text) (5.2.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard<2.10,>=2.9->tensorflow<2.10,>=2.9.0->tensorflow-text) (0.2.8)
Requirement already satisfied: requests-oauthlib>=0.7.0 in c:\users\user\appdata\roaming\python\python39\site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.10,>=2.9->tensorflow<2.10,>=2.9.0->tensorflow-text) (1.3.1)
Requirement already satisfied: importlib-metadata>=4.4 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from markdown>=2.6.8->tensorboard<2.10,>=2.9->tensorflow<2.10,>=2.9.0->tensorflow-text) (4.8.2)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.10,>=2.9->tensorflow<2.10,>=2.9.0->tensorflow-text) (2.0.9)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.10,>=2.9->tensorflow<2.10,>=2.9.0->tensorflow-text) (1.26.7)
Requirement already satisfied: idna<4,>=2.5 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.10,>=2.9->tensorflow<2.10,>=2.9.0->tensorflow-text) (3.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.10,>=2.9->tensorflow<2.10,>=2.9.0->tensorflow-text) (2021.10.8)
Requirement already satisfied: MarkupSafe>=2.1.1 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from werkzeug>=1.0.1->tensorboard<2.10,>=2.9->tensorflow<2.10,>=2.9.0->tensorflow-text) (2.1.1)
Requirement already satisfied: zipp>=0.5 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from importlib-metadata>=4.4->markdown>=2.6.8->tensorboard<2.10,>=2.9->tensorflow<2.10,>=2.9.0->tensorflow-text) (3.6.0)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.10,>=2.9->tensorflow<2.10,>=2.9.0->tensorflow-text) (0.4.8)
Requirement already satisfied: oauthlib>=3.0.0 in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.10,>=2.9->tensorflow<2.10,>=2.9.0->tensorflow-text) (3.2.0)


Thank you for your help!

**Comment by broken** [comment]
Looking more closely at the error, it actually can find the library, it just cannot find the symbol that library is calling. This normally happens when you are using a different version of TF than TF Text. However, I see you are using the same. I've seen this also with Conda, since they build custom versions of TF to use with their environment which can also change the symbol table, but from your paths I assume you are not using Conda either.

Can you pip install a new version of TF & TF Text to see if that works? Try 2.10 or 2.8?

**Comment by HermanTam** [comment]
Yep, thanks! The issue is resolved by upgrading tensorflow & tensorflow-text to 2.10.0. 

tensorflow                   2.10.0
tensorflow-cpu               2.9.0
tensorflow-estimator         2.10.0
tensorflow-gpu               2.10.0
tensorflow-hub               0.12.0
tensorflow_intel             2.10.0
tensorflow-io-gcs-filesystem 0.26.0
tensorflow-text              2.10.0
