### ISSUE TITLE
Tensorflow_text ImportError

### ISSUE THREAD

**Issue by SanJoseCosta** [tensorflow/text#1016]
ImportError                               Traceback (most recent call last)
[<ipython-input-8-3d5792a98fc1>](https://localhost:8080/#) in <module>
      8 import tensorflow as tf
      9 
---> 10 import tensorflow_text

[/usr/local/lib/python3.7/dist-packages/tensorflow_text/__init__.py](https://localhost:8080/#) in <module>
     18 
     19 # pylint: disable=wildcard-import
---> 20 from tensorflow_text.core.pybinds import tflite_registrar
     21 from tensorflow_text.python import keras
     22 from tensorflow_text.python import metrics

ImportError: /usr/local/lib/python3.7/dist-packages/tensorflow_text/core/pybinds/tflite_registrar.so: undefined symbol: _ZN4absl12lts_2022062320raw_logging_internal21internal_log_functionB5cxx11E

---------------------------------------------------------------------------

**Comment by hellodanylo** [comment]
@SanJoseCosta do you mind sharing how you resolved this issue, if at all?
