### ISSUE TITLE
RegexSplitWithOffsets key error

### ISSUE THREAD

**Issue by sudheendrabk-sapper** [tensorflow/text#1024]
Hi,

**I am trying to build tf-text on an aws-linux arm architecture machine. It fails by giving the below error:**

/home/ec2-user/Sapper/sapper-eaas-ief-auto-training/text/tensorflow_text/core/pybinds/BUILD:35:17: Compiling tensorflow_text/core/pybinds/pywrap_fast_bert_normalizer_model_builder.cc failed: (Exit 1): gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 97 arguments skipped)
In file included from ./tensorflow_text/core/kernels/fast_bert_normalizer_model_builder.h:22:0,
                 from tensorflow_text/core/pybinds/pywrap_fast_bert_normalizer_model_builder.cc:19:
./tensorflow_text/core/kernels/fast_bert_normalizer.h: In static member function 'static absl::lts_20220623::StatusOr<tensorflow::text::FastBertNormalizer> tensorflow::text::FastBertNormalizer::Create(const uint32_t*, int, const char*)':
./tensorflow_text/core/kernels/fast_bert_normalizer.h:95:12: error: could not convert 'result' from 'tensorflow::text::FastBertNormalizer' to 'absl::lts_20220623::StatusOr<tensorflow::text::FastBertNormalizer>'
     return result;
            ^~~~~~
At global scope:
cc1plus: warning: unrecognized command line option '-Wno-array-parameter'
cc1plus: warning: unrecognized command line option '-Wno-unknown-warning'
Target //oss_scripts/pip_package:build_pip_package failed to build

**if i try loading a preprocessor model from tf hub it fails to load it giving below error:**

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ec2-user/.local/lib/python3.8/site-packages/tensorflow_hub/module_v2.py", line 106, in load
    obj = tf.compat.v1.saved_model.load_v2(module_path, tags=tags)
  File "/home/ec2-user/.local/lib/python3.8/site-packages/tensorflow/python/saved_model/load.py", line 800, in load
    result = load_partial(export_dir, None, tags, options)["root"]
  File "/home/ec2-user/.local/lib/python3.8/site-packages/tensorflow/python/saved_model/load.py", line 933, in load_partial
    raise FileNotFoundError(
FileNotFoundError: Op type not registered 'RegexSplitWithOffsets' in binary running on ip-10-0-1-150.ap-south-1.compute.internal. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.
 You may be trying to load on a different device from the computational device. Consider setting the `experimental_io_device` option in `tf.saved_model.LoadOptions` to the io_device such as '/job:localhost'.

**Comment by broken** [comment]
This may be a compiler feature thing. Like C++17 is able to resolve it, but not C++11. What version are you compiling with? We use C++17 currently (https://github.com/tensorflow/tensorflow/blob/master/.bazelrc#L354). Can you try building with it?

**Comment by sudheendrabk-sapper** [comment]
Thanks for the response. We were using arm64 architecture on aws-linux ec2 instance and got these errors. We have now switched to x86_64 architecture and pip install did the installation of text for us.

Closing issue.
