### ISSUE TITLE
oss_scripts/build.sh fails

### ISSUE THREAD

**Issue by ravi160822** [tensorflow/text#1040]
```
ERROR: /private/var/tmp/_bazel_user_name/id/external/flatbuffers/BUILD.bazel:84:10: Linking external/flatbuffers/flatc [for host] failed: (Exit 1): cc_wrapper.sh failed: error executing command external/local_config_cc/cc_wrapper.sh @bazel-out/host/bin/external/flatbuffers/flatc-2.params
clang: error: invalid linker name in argument '-fuse-ld=-debugger-tuning=lldb'
Target //oss_scripts/pip_package:build_pip_package failed to build
```

```
Target: arm64-apple-darwin21.6.0
Homebrew clang version 15.0.3
Thread model: posix
```

(`pip install` also fails)

**Comment by broken** [comment]
Correct; we do not have packages for Apple silicon. Check the other issues about this (example: https://github.com/tensorflow/text/issues/823) and you should find tips where others have been able to build it. It is unlikely we'll be building them in the future, but are open to collaborations to get them built, or any changes to the codebase to make the building easier.

In the meantime, I'm going to close this issue as a duplicate so we can consolidate discussions on the topic and minimize fragmentations of info.
