### ISSUE TITLE
Build from source instructions

### ISSUE THREAD

**Issue by mfojtak** [tensorflow/text#114]
The current pypi package is a bit old and there's no instruction how to build a latest one from source.
Also, is there a nightly build somewhere?

Thanks.

**Comment by matthen** [comment]
@broken are there plans to release an updated version on pypi soon? There are various recent features added to master that we would like to use.

**Comment by matthen** [comment]
The pypi release page is a bit confusing. There are older builds with version "1.0.0*" and a more recent one with version "0.1.0"- but `pip install tensorflow-text==0.1.0` fails with `No matching distribution found`.

Specifically we need a build that has the [WordpieceTokenizer changes](https://github.com/tensorflow/text/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Amatthen), and works with tensorflow 1.14.0

**Comment by broken** [comment]
Apologies for the delay. We just did a release today -- 0.1.0 for TF 1.14.0.
TF.Text 0.1.0 has the WordpieceTokenizer changes included.

The build numbering is:
TF.Text 1.x corresponds with TF 2.x
TF.Text 0.x corresponds with TF 1.x

I'll try to make that more clear in the releases.

(A bit of history) We originally planned on TF.Text to only be compatible with TF 2.x. This vision changed when there was interest for supporting TF 1.x, but we had already versioned TF.Text 1.x for TF 2.x, hence the slight mismatching of versions and TF.Text 0.x corresponding with a TF 1.x.

TF changed their build in 1.15 & the latest 2.0 builds. We've been transitioning build systems while also updating the builds to work with their new environment which has delayed things quite a bit. We're very close to having this transition complete. Once we get the next release out I'll update the build instructions.

**Comment by matthen** [comment]
excellent, thanks!

**Comment by mfojtak** [comment]
I tried
```bash
pip install tensorflow-text==1.0.0rc1
```
but it fails with
```
ERROR: Could not find a version that satisfies the requirement tensorflow-text==1.0.0rc1 (from versions: 0.1.0, 1.0.0b0, 1.0.0b1)
ERROR: No matching distribution found for tensorflow-text==1.0.0rc1
```

**Comment by broken** [comment]
mfojtak: We released **0.1.0** for TF 1.14.0.
As  I mentioned above, we are working on the 1.0.0 release for TF 2.0 currently.

**Comment by broken** [comment]
We recently released 2.0 & 1.15 using the new build environments. After some discussions, we decided it is better to match the versioning of TF, so we are skipping ahead. I think the varying versions caused too much confusion, so tf.text 0.1 being for tf 1.14 will be the last one that does not match, and we will abandon 1.0 in favor of 2.0.

I'll keep this issue open until I finish updating the manual build instructions.

**Comment by hanneshapke** [comment]
I have tried to build `tensorflow-text` from source to get the latest updates. Therefore I created a build machine (Ubuntu 16.04), installed bazel and installed the dependencies mentioned in `https://github.com/tensorflow/text/blob/master/oss_scripts/kokoro/linux/release.sh`. 

When I ran `bazel build --crosstool_top=@org_tensorflow//third_party/toolchains/preconfig/ubuntu16.04/gcc7_manylinux2010:toolchain oss_scripts/pip_package:build_pip_package`,  I receive an odd error 

```
ERROR: /home/user_name/text/tensorflow_text/core/kernels/BUILD:47:1: no such package 'base': BUILD file not found in any of the following directories.
 - /home/user_name/text/base and referenced by '//tensorflow_text/core/kernels:regex_split'
```

Which package is meant by `base`? 
Do you have official install steps to build `tensorflow-text` from source? I am running into the fixed issue with the `BertTokenizer`.

Thank you @broken for any hint or advice.

**Comment by broken** [comment]
Sure. I think PR #147 and PR #148 will fix it. There is one more issue with ICU data files that I'm looking at, but I expect we'll release a new release candidate later this week.

**Comment by hanneshapke** [comment]
Hi @broken 

Thank you for your reply and fixes #147 - #149. As you mentioned that issue with the ICU data files is still remaining. Thank you for releasing a new release later this week.

```
l:35:1: C++ compilation of rule '@icu//:icuuc' failed (Exit 1)
src/main/tools/process-wrapper-legacy.cc:58: "execvp(/dt7/usr/bin/gcc, ...)": No such file or directory
Target //oss_scripts/pip_package:build_pip_package failed to build
```

**Comment by broken** [comment]
Hi @hanneshapke, we just released packages for 1.15 and 2.0

I think your error is due to using the toolchain. It is only required for manylinux builds. If your rebuilding TF w/o it, you shouldn't need to build TF Text with it either.

**Comment by hanneshapke** [comment]
Thank you @broken for your explanations!

**Comment by broken** [comment]
I added "build from source instructions" to the main readme. Building TF Text should be very easy now. Note that rebuilding TF is necessary for appropriate linking unless you match their original environment. Feel free to open a new issue (or reopen this one) if you run into issues.
