### ISSUE TITLE
Wheel for Python 3.11 is missing

### ISSUE THREAD

**Issue by bermeitinger-b** [tensorflow/text#1175]
For `tensorflow-text==2.13.0`, there is no wheel for Python 3.11.

Previous versions had this wheel, e.g. installing `keras-nlp` will fallback to `tensorflow-text==2.12.1` and subsequentially install `tensorflow==2.12.0`.

**Comment by sun1638650145** [comment]
Hello, what platform's `whl` file do you need? I have a self-compiled [tutorial](https://github.com/sun1638650145/Libraries-and-Extensions-for-TensorFlow-for-Apple-Silicon/blob/main/tutorials/text/text.md) for Apple Silicon (but it should be similar for other platforms) that might help you.

**Comment by bermeitinger-b** [comment]
Thanks for the offer, I need the usual x86_64 or however that's called.

I've built it myself, the readme is very clear and works. But the compilation takes too long, I'd rather have the "official" wheels.

**Comment by kmkolasinski** [comment]
Hi any updates on this ?

**Comment by rolweber** [comment]
Even in 1.12.1, Python 3.11 was not listed as a supported version. I guess the wheels for py311 were built by mistake.
https://github.com/tensorflow/text/blob/v2.12.1/oss_scripts/pip_package/setup.py#L94-L98
```
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
        'Programming Language :: Python :: 3.10',
        'Programming Language :: Python :: 3 :: Only',
```
