### ISSUE TITLE
Python 3.11 support

### ISSUE THREAD

**Issue by stormlord372** [tensorflow/text#1236]
Hello, do you have any plan to make tensorflow-text available to python 3.11?

**Comment by Jamim** [comment]
Hello @stormlord372,

_I'm not related to this project, so I'm just sharing what I've found._

Although `tensorflow-text` [doesn't support](https://github.com/tensorflow/text/blob/v2.15.0/oss_scripts/pip_package/setup.py#L102-L105) Python 3.11 officially, there are some [wheels](https://packaging.python.org/en/latest/glossary/#term-Wheel) available on [PyPI](https://pypi.org/project/tensorflow-text/#files) for Python 3.11.
You can find some additional information [here](https://github.com/tensorflow/text/issues/1175).

Best!

**Comment by cantonios** [comment]
Yeah, we just started building them for 3.11.  We can easily update the setup.py script.
