### ISSUE TITLE
Does anyone have a precompiled tensorflow-text .whl for linux python 3.8?

### ISSUE THREAD

**Issue by zfarrell13** [tensorflow/text#1237]
see title.  looking for a kind resource before i try and fail to compile myself.

**Comment by zfarrell13** [comment]
linking #878

**Comment by sun1638650145** [comment]
@zfarrell13  Hello, `tensorflow-text` relies on the build of `tensorflow`, and starting from `tensorflow 2.14`, it no longer supports `Python 3.8`.

**Comment by zfarrell13** [comment]
Hey @sun1638650145 , unfortunately I'm working on a project that requires 3.8.  Ive found a precompiled macOS whl and got it working in 3.8.  But, I cannot build a dockerfile for it as docker uses Linux under the hood.  Hope that makes sense.  Ive seen you post precompiled whl files elsewhere, if you know where I can find a 3.8 Linux whl, I'd be forever grateful.

**Comment by zfarrell13** [comment]
@sun1638650145 to be clear, in this project, ive been able to execute tf gin models in python 3.8 by:

pip install tf
pip install tensorflow_text-2.8.2-cp38-cp38-macosx_11_0_arm64.whl
pip installing jax, jaxlib, etc...

what i cant do is build a dockerfile for my project.

when i try to pip install tensorflow_text-2.8.2-cp38-cp38-macosx_11_0_arm64.whl in the dockerfile, i get the following error:

0.380 ERROR: tensorflow_text-2.8.2-cp38-cp38-macosx_11_0_arm64.whl is not a supported wheel on this platform.
------
Dockerfile:35
--------------------
  33 |     RUN pip install --upgrade pip
  34 |     RUN pip install tensorflow==2.12.0
  35 | >>> RUN pip install tensorflow_text-2.8.2-cp38-cp38-macosx_11_0_arm64.whl
  36 |     RUN pip3 install -U scikit-learn==1.2.0
  37 |     RUN pip install -r requirements.txt
--------------------
ERROR: failed to solve: process "/bin/sh -c pip install tensorflow_text-2.8.2-cp38-cp38-macosx_11_0_arm64.whl" did not complete successfully: exit code: 1

which makes sense.  i need a file for: tensorflow_text-2.8.2-cp38-cp38-manylinux_11_0_arm64.whl

in #878, there was a file for this but the link is inactive.  Im confident i can get through the dependencies if i had this file, as ive worked throguh the same dependencies on macos.

**Comment by sun1638650145** [comment]
@zfarrell13 I think I may understand your requirement now. If you need the `manylinux2014_aarch64` version of `tensorflow-text 2.8.2`, you should try building it yourself using the `tensorflow-aarch64` version. Currently, only the `x86-64` version of `whl` for `text` is officially released.

**Comment by zfarrell13** [comment]
@sun1638650145 I was able to build a whl myself, but i could only figure out how to build an x86-64 version for python 3.8.  probably just a matter of number of different combinations of build processes until i figure it out.  in the meantime i built this colab for anyone else struggling: https://colab.research.google.com/drive/1sCAoRpH61cJhrwlDi-VZxpdqoisUUsKc?usp=sharing
