### ISSUE TITLE
Cannot correctly build the `whl` file for Python `3.12`.

### ISSUE THREAD

**Issue by sun1638650145** [tensorflow/text#1297]
The `tensorflow` has started providing pre-compiled `whl` for Python `3.12` since version `2.16`. When will we start providing them? Currently, `bazel` reports a missing `requirement_lock_3_12.txt` file.

**Comment by stefan-it** [comment]
Yeah, `bazel` is so much pain (this whole build system will hopefully get deprecated one day)!

**Comment by DwarKapex** [comment]
I also tried to build tf-text from source with `requirement_lock_3_11.txt`. But it failed with error `cannot import distutils`.
@stefan-it Do you by any chance who to force `bazel` to use python from venv?

**Comment by sun1638650145** [comment]
The issue has been closed as it is now possible to build successfully on Python `3.12`.
