### ISSUE TITLE
unichr() and xrange() were removed in Python 3

### ISSUE THREAD

**Issue by cclauss** [tensorflow/text#13]
[flake8](http://flake8.pycqa.org) testing of https://github.com/tensorflow/text on Python 3.7.1

$ __flake8 . --count --select=E9,F63,F72,F82 --show-source --statistics__
```
./tensorflow_text/python/ops/string_ops.py:29:12: F821 undefined name 'unichr'
    return unichr(codepoint)
           ^
./tensorflow_text/python/ops/wordpiece_tokenizer_test.py:142:19: F821 undefined name 'xrange'
  for docs_idx in xrange(len(tokens)):
                  ^
./tensorflow_text/python/ops/wordpiece_tokenizer_test.py:144:23: F821 undefined name 'xrange'
    for tokens_idx in xrange(len(tokens[docs_idx])):
                      ^
3     F821 undefined name 'unichr'
3
```
__E901,E999,F821,F822,F823__ are the "_showstopper_" [flake8](http://flake8.pycqa.org) issues that can halt the runtime with a SyntaxError, NameError, etc. These 5 are different from most other flake8 issues which are merely "style violations" -- useful for readability but they do not effect runtime safety.
* F821: undefined name `name`
* F822: undefined name `name` in `__all__`
* F823: local variable name referenced before assignment
* E901: SyntaxError or IndentationError
* E999: SyntaxError -- failed to compile a file into an Abstract Syntax Tree

**Comment by broken** [comment]
Thanks; I'll pass this on to get it addressed.

**Comment by broken** [comment]
FYI; PR #24 fixes the tests using xrange.

WRT unichr, that was already gated based on python version, so should not be a problem.

**Comment by cclauss** [comment]
Nice.  This linter test may flag code that does not follow the Python porting best practice, [__use feature detection instead of version detection](https://docs.python.org/3/howto/pyporting.html#use-feature-detection-instead-of-version-detection).
