### ISSUE TITLE
Run model using `WhitespaceTokenizer` from SavedModel Graph Error

### ISSUE THREAD

**Issue by eggie5** [tensorflow/text#130]
I'm using this for some simple tokenization in an Estimator text classifier model. When I try to run my model from SavedModel export, I get this error: `KeyError: 'WhitespaceTokenizeWithOffsets'`

* TF: 1.14.0
* TF-text: 0.1.0

I export my model like this:

```python
def serving_input_receiver_fn():
    """A function that takes no argument and returns a
    `tf.estimator.export.ServingInputReceiver"""
    
    #1 parse the proto w/ the query string
    #2 tokenize the query as "query"
    #3 embedding picks up "query"
    
    serialized_tf_example = tf.placeholder(
        dtype=tf.string,
        shape=[None],
        name='input_example_tensor')
    receiver_tensors = {'examples': serialized_tf_example}
    feature_spec = {'query': tf.FixedLenFeature(1, dtype=tf.string)}
    features = tf.parse_example(serialized_tf_example, feature_spec)
    
    sparse_tokens = tokenizer.tokenize(features["query"]).to_sparse()
    
    features = {'tokens': sparse_tokens}
    
    return tf.estimator.export.ServingInputReceiver(features, receiver_tensors)

classifier.export_saved_model("exports/estimators-BOW-test", serving_input_receiver_fn)
```

However, when I go to test my model, gets an error:

```python
tag_set = "serve"
saved_model_dir = "exports/estimators-BOW-test/1571023056/"
output_tensor_names_sorted = ["dnn/head/Tile:0",
                              "dnn/head/predictions/probabilities:0"]

input_examples = ["taco bell", "taco", "korean", "hancos", "tacos", "mashed potatoes"]
proto_str = make_examples(input_examples, "query")
inputs_feed_dict = {"input_example_tensor:0": proto_str}

CLASS_NAMES = np.array(["CUISINE", "DISH", "RESTAURANT", "ADDRESS"])

with tf.Session(graph=tf.Graph()) as sess:
    loader.load(sess, tag_set.split(','), saved_model_dir)
    outputs = sess.run(output_tensor_names_sorted,
                       feed_dict=inputs_feed_dict)
    for inputs, outputs in zip(input_examples, outputs[1]):
        print(inputs, CLASS_NAMES[np.argmax(outputs)])
```

Error:

```
KeyError: 'WhitespaceTokenizeWithOffsets'
```

I can make this error go away, if in my python process I import:

```
import tensorflow_text as text
```

What is happening? Shouldn't all these ops be on the graph, so for example I could run this in Java or TF Serving(non-python env)??

**Comment by broken** [comment]
The graph does not include the implementation of the ops. We recently added our released ops (which include WhitespaceTokenizer but not case_fold & normalize) to TF serving. Their latest TF 1.x did not include them, but the next release should and their 2.x release should. However, I believe they also have custom build instructions that will allow you to build from head that should include our updates to include tf text.

Java hadn't been a priority. We can look into the work required.

**Comment by eggie5** [comment]
Thanks for helping me understand. I guess I had a fundamental misunderstanding about this package, namely, that any tf-text ops would work on any 1.14 TF runtime, java included. From what I can understand, these are custom ops, not in core TF, but there is a method to include them to the runtime, for example, to make them work w/ Serving. 

Can you give me an example, just so I can understand, what is the work require to get these ops into the Java runtime?

**Comment by broken** [comment]
For Java, I believe you just need to link in the shared libraries provided in the pip package to the java runtime. I cannot provide an example as I have not actually tried it.

**Comment by 17patelumang** [comment]
@eggie5 did you make it work ? if yes could you please share the code ? 
@broken  can you please Java code.
