### ISSUE TITLE
Invalid regex pattern during tokenization

### ISSUE THREAD

**Issue by hanneshapke** [tensorflow/text#158]
When using the Bert or Wordpiece tokenizer, I encounter the error `Invalid pattern (\p{Whitespace}+|[!-/]|[:-@]|[\[-`]|[{-~] ...`.

tensorflow-text version is 2.0.0. 

I thought the issue might be the vocab table, therefore I tried to replicate the BertTokenizer test from the repo. But also this code example fails.

[I created a Colab version for the issue](https://colab.research.google.com/drive/1MpOGneRpPajB8RixhDbPD5U8BEe4Sg89)

I am not sure if it is a bug or a problem with my tokenizer setup.

Thank you for any insights!

**Comment by broken** [comment]
This is a problem with the whitespace pattern. I've reached out to a re2 author to determine where the inconsistency is with the library. Depending on the his response next week, we'll either just work around it or update the library, and should be able to push out a new build.

**Comment by broken** [comment]
The problem is that the character class is defined by ICU, and re2 does not default with linking it in from its github branch. I've replaced it with a native class in #162, and we can reevaluate whether we want to support the ICU classes with the regex op at a later time.

**Comment by broken** [comment]
We released v2.0.1 and v.1.15.1 this morning that includes fixes for this issue. I verified with your colab that this is fixed.

Did you also mention you were wanting to use this with TF Serving?
