### ISSUE TITLE
List of Languages Supported (E.g. English)

### ISSUE THREAD

**Issue by nicholaslaw** [tensorflow/text#16]
Hi, I just wanted to ask what are the languages supported by Tensorflow.text? From what I can see thus far, English, Chinese and German are supported. Thanks for answering! :)

**Comment by broken** [comment]
We currently support all languages supported by ICU (http://site.icu-project.org/home), which should be most languages defined in Unicode. If we release more advanced segmenters, they will probably have a limited language set, but we will make it very clear what their supported languages are.
