### ISSUE TITLE
Error: `U_FILE_ACCESS_ERROR` when build by bazel as `http_archive`

### ISSUE THREAD

**Issue by Alpus** [tensorflow/text#164]
I build `tensorflow/text` from branch `2.0` by `bazel` as a `http_archive`. When I try to use `CaseFoldUTF8Op ` op, I get an error:

```
U_FILE_ACCESS_ERROR: Could not retrieve ICU NFKC_CaseFold normalizer [[{{node CaseFoldUTF8/CaseFoldUTF8}}]]
```

It looks like logic related with [normalization_data.c](https://github.com/tensorflow/text/blob/master/third_party/icu/data/normalization_data.c) doesn't work, but I can't understand why.

I use bazel `0.24.1`

Do you have any suggestions?

**Comment by broken** [comment]
So tensorflow_text is a http_archive in another repository right? If this is the case, you need to maker certain your including our build & patch for ICU.

If your building straight into TF, they use a similar method of patching in a minimal amount of ICU data. I think if you build two different ICU data targets, that part should be fine and you don't need to attempt to combine the data files (or create a new one of the combined data). However, you will need to combine the patches for ICU to know where to look for the individual data files.
