### ISSUE TITLE
Unable to train model with Keras API and tensorflow_text

### ISSUE THREAD

**Issue by jdeason23** [tensorflow/text#174]
Trying to train a model using the example from the README file, but it doesn't work: 

    import tensorflow as tf
    import tensorflow_text as text
    model = tf.keras.Sequential([
    tf.keras.layers.InputLayer(input_shape=(None,), dtype='int32', ragged=True),
    text.keras.layers.ToDense(pad_value=0, mask=True),
    tf.keras.layers.Embedding(100, 16),
    tf.keras.layers.LSTM(32),
    tf.keras.layers.Dense(32, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
    ])

ERROR:
ValueError: The two structures don't have the same nested structure.

First structure: type=TensorSpec str=TensorSpec(shape=(), dtype=tf.string, name=None)

Second structure: type=RaggedTensor str=tf.RaggedTensor(values=Tensor("input_1/flat_values:0", shape=(None,), dtype=int32), row_splits=Tensor("input_1/row_splits_0:0", shape=(None,), dtype=int64))

More specifically: Substructure "type=RaggedTensor str=tf.RaggedTensor(values=Tensor("input_1/flat_values:0", shape=(None,), dtype=int32), row_splits=Tensor("input_1/row_splits_0:0", shape=(None,), dtype=int64))" is a sequence, while substructure "type=TensorSpec str=TensorSpec(shape=(), dtype=tf.string, name=None)" is not
Entire first structure:
.
Entire second structure:
.

**Comment by broken** [comment]
It looks like your input is a normal tensor and not actually ragged, which you specified as your InputLayer.

Can you share a sample of your input?

**Comment by jdeason23** [comment]
### Overview of the steps (details below)
read in a csv file of labeled data with 2 columns, review_content and label
make the review_content and label 2 different numpy.ndarray
put the ndarrays into 2 tensors
make datasets
feed the datasets into .fit()

TRAIN_FILE = 'train.csv' 
VAL_FILE = 'val.csv'
EPOCHS = 10

file content similar to:
review_content,label
'I really liked this movie',1
"not my favorite",0

### training data
review_data_df = pd.read_csv(TRAIN_FILE)
reviews = review_data_df['review_content'].str.lower()
reviews_data_array = reviews.values
labels = review_data_df['label']
reviews_labels_array = labels.values
train_X = tf.constant(reviews_data_array)
train_y = tf.constant(reviews_labels_array)

### validation data
validations = pd.read_csv(VAL_FILE)
val_reviews = validations['review_content'].str.lower()
val_labels = validations['label']
validation_X = tf.constant(val_reviews)
validation_y = tf.constant(val_labels)

train_dataset = tf.data.Dataset.from_tensor_slices((train_X, train_y))
validation_dataset = tf.data.Dataset.from_tensor_slices((validation_X,validation_y))

history = model.fit(train_dataset,
                     validation_data=validation_dataset,
                     epochs=EPOCHS,
                     verbose=1
                    )

**Comment by broken** [comment]
The main issue I see is that you have no preprocessing step. You may have this in your actual code, but what your supplying to your model as above is a full sentence. This means your tensor is not actually ragged. I expect you want to tokenize it first.

Here is an example in Google colab (with the main code below):
https://colab.research.google.com/drive/10CqphJfrmyQSEuZegQ_raausMexQXHKf

```
def _CreateTable(vocab, num_oov=1):
  init = tf.lookup.KeyValueTensorInitializer(
      vocab,
      tf.range(tf.size(vocab, out_type=tf.int64), dtype=tf.int64),
      key_dtype=tf.string,
      value_dtype=tf.int64)
  return tf.lookup.StaticVocabularyTable(
      init, num_oov, lookup_key_dtype=tf.string)

reviews_data_array = ['I really liked this movie', 'not my favorite']
reviews_labels_array = [1,0]
train_x = tf.constant(reviews_data_array)
train_y = tf.constant(reviews_labels_array)

a = _CreateTable(['I', 'really', 'liked', 'this', 'movie', 'not', 'my', 'favorite'])

def preprocess(data, labels):
  t = text.WhitespaceTokenizer()
  data = t.tokenize(data)
  # data = data.merge_dims(-2,-1)
  ids = tf.ragged.map_flat_values(a.lookup, data)
  return (ids, labels)

train_dataset = tf.data.Dataset.from_tensor_slices((train_x, train_y)).batch(2)
train_dataset = train_dataset.map(preprocess)

model = tf.keras.Sequential([
  tf.keras.layers.InputLayer(input_shape=(None,), dtype='int64', ragged=True),
  text.keras.layers.ToDense(pad_value=0, mask=True),
  tf.keras.layers.Embedding(100, 16),
  tf.keras.layers.LSTM(32),
  tf.keras.layers.Dense(32, activation='relu'),
  tf.keras.layers.Dense(1, activation='sigmoid')
])

model.compile(
  optimizer="rmsprop",
  loss="binary_crossentropy",
  metrics=["accuracy"])

output = model.fit(train_dataset, epochs=1, verbose=1)
print(output)
```

**Comment by dzlab** [comment]
@broken the Google colab link you provided is not publicly available!!

**Comment by broken** [comment]
ugh! When I opened it up, apparently it only allowed to certain groups. I'm adding the colab to the examples subdirectory instead (pr #201) to make sure it is available.

**Comment by broken** [comment]
https://github.com/tensorflow/text/blob/master/examples/keras_example_174.ipynb
