### ISSUE TITLE
2.1.0 RC builds

### ISSUE THREAD

**Issue by connorbrinton** [tensorflow/text#198]
First of all, thanks for maintaining TF Text! 😄

Are there any plans to build release candidate releases for TF Text? Release candidate builds ([2.1.0rc0](https://github.com/tensorflow/tensorflow/releases/tag/v2.1.0-rc0) and [2.1.0rc1](https://github.com/tensorflow/tensorflow/releases/tag/v2.1.0-rc1)) have been published for the main TensorFlow package, but corresponding releases aren't available yet for TF Text. Instructions for installing TF Text state:

> When installing TF Text with pip install, please note the version of TensorFlow you are running, as you should specify the corresponding version of TF Text.

If release candidate builds could be created, that would be super helpful for me, since I'm unable to easily use TF 2.0.0 due to [these changes](https://github.com/tensorflow/tensorflow/pull/32758) not making it into the release 😅

**Comment by broken** [comment]
Sure; we can do a 2.1.0rc release this week.

**Comment by broken** [comment]
We just released 2.1.0rc0. I tested against TF 2.1.0rc1, but should work for rc0 as well.
