### ISSUE TITLE
how to deal with raggedtensor in the model output

### ISSUE THREAD

**Issue by dzlab** [tensorflow/text#202]
I have a seq2seq model like this
```python
model = Sequential([
  InputLayer(input_shape=(None,), dtype='int64', ragged=True),
  tftext.keras.layers.ToDense(pad_value=0, mask=True),
  Embedding(src_vocab, n_units, input_length=src_timesteps, mask_zero=True),
  LSTM(n_units),
  RepeatVector(tar_timesteps),
  LSTM(n_units, return_sequences=True),
  TimeDistributed(Dense(tar_vocab, activation='softmax'))
])
```
And I am build the dataset from a pair of engilish-german sentences like this
```python
def basic_preprocess(src, dst):
  # Preprocess
  rt_src = preprocess(src)
  rt_dst = preprocess(dst)
  # Encode tokens
  features = tf.ragged.map_flat_values(en_vocab_table.lookup, rt_src)
  labels = tf.ragged.map_flat_values(ge_vocab_table.lookup, rt_dst)

  return features, labels
```
My problem is that when I fit the model I get the following error as the output is ragged (while input is not longer ragged)
```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/tensorflow-2.0.0/python3.6/tensorflow_core/python/util/nest.py in assert_same_structure(nest1, nest2, check_types, expand_composites)
    317     _pywrap_tensorflow.AssertSameStructure(nest1, nest2, check_types,
--> 318                                            expand_composites)
    319   except (ValueError, TypeError) as e:

ValueError: The two structures don't have the same nested structure.

First structure: type=TensorSpec str=TensorSpec(shape=(None,), dtype=tf.int64, name=None)

Second structure: type=RaggedTensor str=tf.RaggedTensor(values=Tensor("input_1/flat_values:0", shape=(None,), dtype=int64), row_splits=Tensor("input_1/row_splits_0:0", shape=(None,), dtype=int64))

More specifically: Substructure "type=RaggedTensor str=tf.RaggedTensor(values=Tensor("input_1/flat_values:0", shape=(None,), dtype=int64), row_splits=Tensor("input_1/row_splits_0:0", shape=(None,), dtype=int64))" is a sequence, while substructure "type=TensorSpec str=TensorSpec(shape=(None,), dtype=tf.int64, name=None)" is not

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
```
How should I fix this?

**Comment by broken** [comment]
Apologies for the delayed response. We've all been on vacation and are just getting back now.

Here is an example I made for another Keras / ragged question (#174).
https://colab.research.google.com/github/tensorflow/text/blob/master/examples/keras_example_174.ipynb

Does that help. Nothing jumps out at me immediately looking at your code. Can you get an example working in colab that shows the error?
https://colab.research.google.com/

**Comment by dzlab** [comment]
happy new year and no worries, I expected a delay as it was the holiday season, hope you enjoyed your time.

I am aware of the example above (or may be similar one) it was very helpful to start with this library.

Here is my example that I was working on when I did hit the error  https://colab.research.google.com/drive/1HAZvUmBI7PjyyPo-VKxY8l1kQIBQp5mh

**Comment by broken** [comment]
I've asked somebody on the team that has contributed to the keras training code to take a look.

**Comment by markomernick** [comment]
Hi @dzlab,

It looks like your input data is not actually a RaggedTensor. You can inspect your train_ds with:

for element in train_ds.take(1):
  print(element)

and see that it contains two standard tf.tensors, which is why the input is giving an (admittedly not very useful) error message. We're working on fixing this as part of adding broader CompositeTensor support to Keras.

**Comment by dzlab** [comment]
Oh you're right, this is what is happening:
```python
>>> preprocess('Hi')
<tf.Tensor: id=44330, shape=(1,), dtype=string, numpy=array([b'hi'], dtype=object)>

>>> preprocess(['Hi'])
<tf.RaggedTensor [[b'hi']]
```
Batching with `.batch(bs)`  before calling `.map(basic_preprocess)` fixed this issue.
Though I still have problems when trying to fit, will try to spend more time investigating this.
