### ISSUE TITLE
Non-existent components references in docs & comments

### ISSUE THREAD

**Issue by kovasb** [tensorflow/text#203]
Hi, thanks for this awesome project. We are taking a look at this lib for some NLP research projects at Twitter and it looks very promising. 

Some things I found browsing the project:

There is a reference to "TextExtractor" at 
https://github.com/tensorflow/text/blob/9a92e9716e58460203d59192037eaa217d958f00/docs/api_docs/python/text/sentence_fragments.md

and also in the docstring of the function at https://github.com/tensorflow/text/blob/e617710bd1ee511d02fef35a08c6a7c0da5c86e2/tensorflow_text/python/ops/sentence_breaking_ops.py#L51

There is a reference to the "SAFT Tokenization library" in 
https://github.com/tensorflow/text/blob/0429f3cae7d297e02e4c00edfeaf99168fa4a875/tensorflow_text/python/ops/create_feature_bitmask_op.py#L18

From the context these sound very useful. Is there a timeline for incorporating them into the code?

Either way, it might be good to remove these references for the time being to avoid confusion.

**Comment by broken** [comment]
Thanks for pointing this out. TF text is basically the successor to that project, and this looks like it was code not looked at very closely when it was copied. We should clean it up.

**Comment by broken** [comment]
It looks like the code/comments was updated some time ago, but this was never closed.
