### ISSUE TITLE
TextVectorization layer vs TensorFlow Text

### ISSUE THREAD

**Issue by dzlab** [tensorflow/text#206]
The latest TF version 2.1 added a new Keras layer for text processing in the graph which is `TextVectorization` . This layers seems to support custom tokenization and all typical preprocessing stuff ([here a detailed article on how to use it](https://dzlab.github.io/dltips/en/tensorflow/textvectorization-preprocessing/)). 
```python
vectorize_layer = TextVectorization(
    standardize=custom_standardization,
    max_tokens=max_features,
    output_mode='int',
    output_sequence_length=400)
```
What does this means for TF Text which now still have to be used with `ToDense` layer as very few layers support RaggedTensors? And when to use each one of the two?

**Comment by markomernick** [comment]
Hi @dzlab -

We are working hard on increasing the number of layers that support RaggedTensors within Keras - stay tuned for more on that soon.

With regard to tf.text and TextVectorization - the same team is working on both of them. By creating TextVectorization, we gave Keras users the ability to do standard tokenization and preprocessing right out of the box, while offering more complex text processing through the tf.text repo.

**Comment by sebawastaken** [comment]
Hi,
i am trying to construct an tf.estimator from a keras model which includes text preprocessing at inference an serve it with tf-serving. I have a working version of it, but i want to replace the preprocessing part with tf.text or TextVectorization. Is it possible to include one of them in an estimator so i can use an exporter in the eval_spec?  Which one is the right choice.

**Comment by markomernick** [comment]
Hi @sebawastaken -

The TextVectorization layer uses core TF primitives only, so you should be able to use that in an Estimator and tf.serving without trouble - all you have to do is call the layer object on some tensors and use the output elsewhere in your model_fn or input_fn. @broken - are all the tf.text ops compatible with tf.serving as well?

**Comment by broken** [comment]
The code to get all of TF Text 2.0.1 ops into tf.serving is now in (as of today).

**Comment by i-chaochen** [comment]
May I ask what's the difference between Tokenizer(fit_on_texts, texts_to_sequences and pad_sequences) and TextVectorization layer?

It seems they're doing the same thing.
