### ISSUE TITLE
NotImplementedError: Saving is not yet supported for TextVectorization layers.

### ISSUE THREAD

**Issue by dzlab** [tensorflow/text#210]
I'm defining a TextVectorization layer like this
```python
decoder_vectorize = TextVectorization(
  name='de_vectorize',
  standardize = 'lower_and_strip_punctuation',
  split       = 'whitespace',
  max_tokens  = config.tar_vocab,
  output_mode ='int', 
  output_sequence_length=config.tar_timesteps
)
```
Then after training, I try to save the model but i'm hitting errors
```python
>>> model.save('model.h5')
/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/backend.py in <listcomp>(.0)
   3312   if context.executing_eagerly():
-> 3313     return [x.numpy() for x in tensors]
   3314   elif ops.inside_function():  # pylint: disable=protected-access
   3315     raise RuntimeError('Cannot get value inside Tensorflow graph function.')

AttributeError: 'TrackableWeightHandler' object has no attribute 'numpy'

>>> model.save('model.tf', save_format='tf')
/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/layers/preprocessing/text_vectorization.py in fail(_)
    295     def fail(_):
    296       raise NotImplementedError(
--> 297           "Saving is not yet supported for TextVectorization layers.")
    298     self._table._list_extra_dependencies_for_serialization = fail  # pylint: disable=protected-access
    299 

NotImplementedError: Saving is not yet supported for TextVectorization layers.
```

This is on a nightly TF version `2.2.0-dev20200122`. Is there a workaround?

**Comment by swierchola** [comment]
Similar problem for TF 2.1.0 and [end-to-end text classification example](https://colab.research.google.com/drive/1RvCnR7h0_l4Ekn5vINWToI9TNJdpUZB3) from release notes.

Is there a way to save and load model with TextVectorization layer (it is very cool and useful feature)? How TextVectorization can be used in production pipelines without model saving not supported?

```
model.save('test')
```
```
.../tensorflow_core/python/saved_model/save.py in list_extra_dependencies(self, obj)
    134   def list_extra_dependencies(self, obj):
    135     return obj._list_extra_dependencies_for_serialization(  # pylint: disable=protected-access
--> 136         self._serialization_cache)
    137 
    138   def list_functions(self, obj):

../keras/layers/preprocessing/text_vectorization.py in fail(_)
    288     def fail(_):
    289       raise NotImplementedError(
--> 290           "Saving is not yet supported for TextVectorization layers.")
    291     self._table._list_extra_dependencies_for_serialization = fail  # pylint: disable=protected-access
    292 

NotImplementedError: Saving is not yet supported for TextVectorization layers.
```

**Comment by markomernick** [comment]
Hi @dzlab, @swierchola -

We're working on the extensions we need to the core TF saving APIs to enable this - the fix has gone in internally and you should see it in the nightlies soon.

**Comment by moelliDo** [comment]
Hi, 

I'm using the StructuredDataClassifier of Auto-Keras and after the model has been trained successfully, I get the same error as above whenever I try to save the model: 

> Traceback (most recent call last):
  File "vanilla_autokeras_bpi19.py", line 113, in <module>
    model_to_export.save("bpi19_keras_model_i.h5")
  File "/home/user/autokeras/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/network.py", li$
    signatures, options)
  File "/home/user/autokeras/lib/python3.6/site-packages/tensorflow_core/python/keras/saving/save.py", line $
    model, filepath, overwrite, include_optimizer)
  File "/home/user/autokeras/lib/python3.6/site-packages/tensorflow_core/python/keras/saving/hdf5_format.py"$
    save_weights_to_hdf5_group(model_weights_group, model_layers)
  File "/home/user/autokeras/lib/python3.6/site-packages/tensorflow_core/python/keras/saving/hdf5_format.py"$
    weight_values = K.batch_get_value(weights)
  File "/home/user/autokeras/lib/python3.6/site-packages/tensorflow_core/python/keras/backend.py", line 3270$
    return [x.numpy() for x in tensors]
  File "/home/user/autokeras/lib/python3.6/site-packages/tensorflow_core/python/keras/backend.py", line 3270$
    return [x.numpy() for x in tensors]
AttributeError: 'TrackableWeightHandler' object has no attribute 'numpy'

Are there any updates regarding this issue?

**Comment by dzlab** [comment]
The issue related to TextVectorization is fixed, if you try the tf nightly version. 
```
$ pip install -q tf-nightly
```

**Comment by swierchola** [comment]
@dzlab @markomernick @moelliDo saving model with TextVectorization works, but there is problem with loading saved model. I created new ticket [Incompatible shapes when loading model with TextVectorization and Embedding + Conv1D #38250](https://github.com/tensorflow/tensorflow/issues/38250) for this new issue. I'm wondering if you had same problems. We can continue discussion in a new ticket to not make a mess in this closed one.

**Comment by hcs-bernardo-rufino** [comment]
I know this is closed, but i'm having the same issue with tensorflow 2.8.

```python
VOCAB_SIZE = 20_000
encoder = tf.keras.layers.TextVectorization(
    max_tokens=VOCAB_SIZE,
    standardize='lower',
    output_mode='int')
encoder.adapt(train_dataset.map(lambda text, label: text))
```

The error:

NotImplementedError: Save or restore weights that is not an instance of `tf.Variable` is not supported in h5, use `save_format='tf'` instead. Received a model or layer TextVectorization with weights [<keras.layers.preprocessing.index_lookup.VocabWeightHandler object at 0x0000025548A6C6A0>]

**Comment by kannanwisen** [comment]
For me h5py worked.

model.save("model.h5py")

model = load_model("model.h5py")
