### ISSUE TITLE
KeyError: 'WhitespaceTokenizeWithOffsets'  when trying to run SavedModel 

### ISSUE THREAD

**Issue by 17patelumang** [tensorflow/text#232]
I'm using this for simple tokenization in text classifier model. When I try to run my model from SavedModel export file, I get this error: KeyError: 'WhitespaceTokenizeWithOffsets'

    TF: 1.14.0
    TF-text: 0.1.0

Error:
   KeyError: 'WhitespaceTokenizeWithOffsets'

When I do "import tensorflow_text" it works . 

Having read different blogs and issues on tensorflow/text and tensorflow/serving git repo , I found that issue was TF Text ops is not included in core graph . 

From https://github.com/tensorflow/serving/issues/1490  including .so explicitly in Java at run time using throws segmentation fault . 

Reading the reply from issue here - https://github.com/tensorflow/text/issues/130 , there was no code of Java provided where adding .so file explicitly we are able to solve this issue. Is there any java code available ?

**Comment by edloper** [comment]
> KeyError: 'WhitespaceTokenizeWithOffsets'
Could you please provide the complete stack trace for the KeyError exception?

> including .so explicitly in Java at run time using throws segmentation fault
Are you sure that you're using the right .so version for whatever platform you're on?  broken@ suggests finding the right .so file this way: https://github.com/tensorflow/serving/issues/1490#issuecomment-592249594

> Is there any java code available ?
It looks like alpsholic@ provided some here: https://github.com/tensorflow/serving/issues/1490#issuecomment-598539043

**Comment by 17patelumang** [comment]
@edloper  tensorflow/serving#1490 (comment) this wroks

**Comment by gregbillock** [comment]
Thanks! Going to close this...
