### ISSUE TITLE
2.2.0-rc0 Release

### ISSUE THREAD

**Issue by terrykong** [tensorflow/text#243]
Howdy,

Can we expect a 2.2.0-rc0 release anytime soon?

Thanks!

**Comment by markomernick** [comment]
We're working on it as we speak! Stay tuned for more updates.

**Comment by terrykong** [comment]
@markomernick awesome. looking forward to it!

**Comment by broken** [comment]
We just released 2.2.0rc1.  Thanks for your patience!
