### ISSUE TITLE
vocab_lookup_table must be a LookupInterface

### ISSUE THREAD

**Issue by chikubee** [tensorflow/text#27]
Couldn't run the wordpiece tokenizer, 
vocab_lookup_table must be a LookupInterface
what is the format of the file it is looking for? 
Any Leads?

**Comment by thuang513** [comment]
LookupInterface is a base class for performing lookups. There are concrete subclasses (such as StaticHashTable [1], StaticVocabularyTable [2]) that dictate how the lookups are done, how is it initialized (e.g. from a tensor, from a string file) and how to deal with out of vocabulary values.

[1] https://github.com/tensorflow/tensorflow/blob/3699977134badccb7032fa6921d70e01ba8fdf7d/tensorflow/python/ops/lookup_ops.py#L106
[2] https://www.tensorflow.org/api_docs/python/tf/lookup/StaticHashTable
[3] https://www.tensorflow.org/api_docs/python/tf/lookup/StaticVocabularyTable

**Comment by chikubee** [comment]
Thanks for the reply, I did not go to the depths but wanted to try out
the *word
piece Tokenizer,* found its implementation in the *BERT repository.*
I have a doubt about how it can be used independently, to create your own
dynamic vocabulary i tried this script
https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/data_generators/text_encoder_build_subword.py.
But the results were not as expected, it recognizes the token if not
present as unknown and no msaking was observed. Is there a documentation
available for this?


Thanks for the help,
Ankita Makker

**Comment by broken** [comment]
The script you linked to is an independent implementation of a different subword tokenizer. This is not for generating a wordpiece vocab.

A wordpiece vocab you can use is part of the public BERT models. You should find a vocab.txt in the model zip files.
https://github.com/google-research/bert

Wordpiece does not perform the masking in BERT. The wordpiece op here only splits word tokens into subwords and maps them to the IDs. I just noticed there wasn't an example in our colab (I'll add that soon), but you can see an example of this in the blog post announcement.
https://medium.com/tensorflow/introducing-tf-text-438c8552bd5e

**Comment by chikubee** [comment]
Hey, this works using the vocab.txt from BERT and following the createTable procedure as described in the blog, Thanks.
I was trying to create a new wordpiece vocabulary earlier which is why I was using the tensor2tensor script shared in https://github.com/google-research/bert for learning a new wordpiece vocab.
