### ISSUE TITLE
Please fix setup.py to allow tensorflow-gpu

### ISSUE THREAD

**Issue by sbarman-mi9** [tensorflow/text#28]
Please fix setup.py to allow tensorflow-gpu:

Old: 
install_requires=[
        'tensorflow==2.0.0b0',
   ],

New:
install_requires=[
        'tensorflow-gpu >=2.0.0b0',
 ],
extras_require = [ 'tensorflow >=2.0.0b0', ]

Thanks,
Snehasish

**Comment by broken** [comment]
Snehasish, unfortunately, we don't have a good solution for this. By making the suggested change it forces installs of tensorflow-gpu. As it is, you can install tensorflow-gpu after and it should work; so instead, I added it as an extras_require.

**Comment by sbarman-mi9** [comment]
Thank you.
