### ISSUE TITLE
Dependency lib ICU checksum is incorrect

### ISSUE THREAD

**Issue by hyperloglogy** [tensorflow/text#303]
in the current WORKSPACE, ICU sha256 = `dfc62618aa4bd3ca14a3df548cd65fe393155edd213e49c39f3a30ccd618fc27`

```
http_archive(
    name = "icu",
    strip_prefix = "icu-release-64-2",
    sha256 = "dfc62618aa4bd3ca14a3df548cd65fe393155edd213e49c39f3a30ccd618fc27",
    urls = [
        "https://github.com/unicode-org/icu/archive/release-64-2.zip",
    ],
    build_file = "//third_party/icu:BUILD.bzl",
    patches = ["//third_party/icu:udata.patch"],
    patch_args = ["-p1", "-s"],
)
```
however, the real checksum is `10cd92f1585c537d937ecbb587f6c3b36a5275c87feabe05d777a828677ec32f`

to verify: 
```
wget https://github.com/unicode-org/icu/archive/release-64-2.zip
shasum -a 256 ./release-64-2.zip
```

**Comment by broken** [comment]
Yep, we noticed this as well. There are binaries within the release that GitHub used to not include in the zip archive. They recently updated to include these data files. Consequently, this also almost doubled the size of the zip file.

We added backup dependency locations in https://github.com/tensorflow/text/commit/c35122b2cec198887cf40932fe3bca0a6f2e9fc0
