### ISSUE TITLE
Demonstrating compatibility issue with TFX/ potential issue with multiple workers

### ISSUE THREAD

**Issue by tommywei110** [tensorflow/text#315]
It was found Tensorflow_text would have error:
`RuntimeError: tensorflow.python.framework.errors_impl.NotFoundError: Op type not registered 'RegexSplitWithOffsets' in binary running on penguin. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) tf.contrib.resampler should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed. [while running 'Analyze/ComputeDeferredMetadata'] [while running 'Run[Transform]']`

And this error is _potentially_ caused by tf_text ops not being properly imported on multiple workers when trying to run the pipeline in parallel.

In the example code, change the parameter `direct_num_workers` to 0, would cause the error to occur as the runner would try to use multiple workers

More detail is in the repo.

https://github.com/tommywei110/demonstrateTFX-TFText

**Comment by broken** [comment]
Thanks; I'm doing to consolidate this with #311

**Comment by xiaoyunwu** [comment]
any update on this?
