### ISSUE TITLE
End offset in `wordpiece_tokenizer` inacurrate when `max_bytes_per_token` is set along with `use_unknown_token`

### ISSUE THREAD

**Issue by vbod** [tensorflow/text#344]
**Context**

When one uses the WordPiece tokenizer and sets `max_bytes_per_token` and `use_unknown_token` together, information on the length of any token longer than `max_bytes_per_token` is lost for `unknown_token.size()` (default: 5). This is an issue for a end-user because: 
- the user cannot rely on `end_offset` vector: this may crash any application built upon this library because it receives a length of 5 instead of the real one making it impossible to reconstruct substring. Note that it happens quite often in "real-world" use-cases: for me I was scrapping a Wikipedia dump with some pages having long words in different languages (e.g. "สานักยุทธศาสตร์และการวางแผนเศรษฐกิจมหภ" in Thaï which has longer than the default 100 in UTF-8).
- it is inconsistent with the behavior in `NoTokenFound()` where the actual size of the token is set instead of `unknown_token.size()`.

**Fix proposed**

It's actually quite simple, it comes from [this line](https://github.com/tensorflow/text/blob/master/tensorflow_text/core/kernels/wordpiece_tokenizer.cc#L225) and we'd just need to change for:
```C++
LookupStatus WordpieceTokenize(
    const absl::string_view& token, const int max_bytes_per_token,
    const int max_chars_per_subtoken, const std::string& suffix_indicator,
    bool use_unknown_token, const std::string& unknown_token,
    bool split_unknown_characters, const WordpieceVocab* vocab_map,
    std::vector<std::string>* subwords, std::vector<int>* begin_offset,
    std::vector<int>* end_offset, int* num_word_pieces) {
  int token_len = token.size();
  if (token_len > max_bytes_per_token) {
    begin_offset->push_back(0);
    *num_word_pieces = 1;
    if (use_unknown_token) {
      end_offset->push_back(token_len);
      subwords->emplace_back(unknown_token);
    } else {
      subwords->emplace_back(token);
      end_offset->push_back(token.size());
    }
    return LookupStatus::OK();
  }
  return TokenizeL2RGreedy(token, max_bytes_per_token, max_chars_per_subtoken,
                           suffix_indicator, use_unknown_token, unknown_token,
                           split_unknown_characters, vocab_map, subwords,
                           begin_offset, end_offset, num_word_pieces);
}
```
There might be caveats in doing so that I haven't realized, but so far this bug forces to set `max_bytes_per_token` to the maximum integer value in order to avoid any bug, which is a pitty as there's indeed useless lookups that could be avoided.

If you're OK with this fix though, I can create a PR if you want.

**Comment by thuang513** [comment]
Sorry for the late reply, and thanks for reporting this issue @vbod! feel free to create and send a PR!

**Comment by vbod** [comment]
Will do when I come back from vacation :-)

**Comment by vbod** [comment]
@thuang513 I created a PR (#380 ) a few weeks ago but I don't really understand if I need to do something more (seems like it's pending at an internal Google state).
