### ISSUE TITLE
Documentation website ?

### ISSUE THREAD

**Issue by Conchylicultor** [tensorflow/text#351]
It seems that the `tensorflow_text` API cannot be found anywhere on the TF website. Only the API doc from github seems to exists. Is it expected ?

I believe adding a subsite tensorflow/text would help discoverability and usability.

+@yashk2810 which may have more context.

**Comment by yashk2810** [comment]
Yeah, they don't have a full subsite yet. If they want I can set it up, but the tf_text folks haven't reached out to us yet about a subsite.

**Comment by broken** [comment]
We reached out internally initially, but maybe not to the right people or were too far in infancy. @yashk2810 I'd be interested in working with you to set up a subsite.

**Comment by yashk2810** [comment]
Sounds good to me 😄

**Comment by Conchylicultor** [comment]
Is there any update on this ? As far as I know there is still no website.
For example, many users ask us what are the subword tokenizer. Finding the available tokenizers currently is not straightforward at all, as searching for the API is quite hard.

**Comment by broken** [comment]
We're starting this up again with the new year. We didn't have the time to create more tutorials, guides, & models to fill up the subsite. The goal is to have this put together by early April.

**Comment by ariG23498** [comment]
I would also like to add that the documentation does not render properly with the Github pages.
While the [index page](https://tensorflow.github.io/text/api_docs/python/) is rendered in markdown, the [markdown files](https://tensorflow.github.io/text/api_docs/python/text.md) that are (most probably) generated from docstrings are not rendered properly.

## Screenshots
### Index page:
![image](https://user-images.githubusercontent.com/36856589/114417601-5b771b00-9bcf-11eb-85b7-239bde4352f6.png)

### text.md page:
![image](https://user-images.githubusercontent.com/36856589/114417631-629e2900-9bcf-11eb-88b3-3f6d9efe9f36.png)

**Comment by yashk2810** [comment]
The markdown is not designed to be rendered on github pages. We are working on bringing it to tensorflow.org.

**Comment by broken** [comment]
This is now available: https://www.tensorflow.org/text/api_docs/python/text

**Comment by broken** [comment]
Closing this as we have a whole subsite now dedicated to the api with tutorial and guides on [https://www.tensorflow.org/text](https://www.tensorflow.org/text)
