### ISSUE TITLE
Problem with wheels in older OSX versions

### ISSUE THREAD

**Issue by elyase** [tensorflow/text#375]
Hi guys,

it seems there is an issue with wheels in older OSX versions. In (OSX 10.13 High Sierra):
```
tensorflow==2.3.0
tensorflow-addons==0.11.1
tensorflow-text==2.3.0
```
**Error trace:**
```
python-3.7.7 ❯ python                                                        (base)
Python 3.7.7 (default, Aug 18 2020, 20:34:46)
[Clang 10.0.0 (clang-1000.10.44.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from tensorflow_text.python.ops.bert_tokenizer import BertTokenizer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/elyase/.direnv/python-3.7.7/lib/python3.7/site-packages/tensorflow_text/__init__.py", line 22, in <module>
    from tensorflow_text.python.ops import *
  File "/Users/elyase/.direnv/python-3.7.7/lib/python3.7/site-packages/tensorflow_text/python/ops/__init__.py", line 23, in <module>
    from tensorflow_text.python.ops.bert_tokenizer import BertTokenizer
  File "/Users/elyase/.direnv/python-3.7.7/lib/python3.7/site-packages/tensorflow_text/python/ops/bert_tokenizer.py", line 30, in <module>
    from tensorflow_text.python.ops.normalize_ops import case_fold_utf8
  File "/Users/elyase/.direnv/python-3.7.7/lib/python3.7/site-packages/tensorflow_text/python/ops/normalize_ops.py", line 28, in <module>
    gen_normalize_ops = load_library.load_op_library(resource_loader.get_path_to_datafile('_normalize_ops.dylib'))
  File "/Users/elyase/.direnv/python-3.7.7/lib/python3.7/site-packages/tensorflow/python/framework/load_library.py", line 58, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: dlopen(/Users/elyase/.direnv/python-3.7.7/lib/python3.7/site-packages/tensorflow_text/python/ops/_normalize_ops.dylib, 6): Symbol not found: ____chkstk_darwin
  Referenced from: /Users/elyase/.direnv/python-3.7.7/lib/python3.7/site-packages/tensorflow_text/python/ops/_normalize_ops.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/elyase/.direnv/python-3.7.7/lib/python3.7/site-packages/tensorflow_text/python/ops/_normalize_ops.dylib
```

This [potentially relevant issue](https://github.com/nodegui/nodegui/issues/391) provides the following resolution:

> Need to add CMAKE_OSX_DEPLOYMENT_TARGET to an older version of mac than the latest to make the binary compatible.

Not sure what the bazel equivalent would be.

**Comment by broken** [comment]
Thanks for pointing this out, we'll take a look.

**Comment by mchari** [comment]
@broken , any update on this ? 
Thanks!

**Comment by broken** [comment]
We build on 10.14 hardware (same as TF), so I'm surprised this states we limit to MacOS 10.15. Though, this issue is asking about an even earlier version - 10.13. Does the TF package work on 10.13? Talking with their dev unit, they expect a min version of 10.14 (at least with current builds).

**Comment by thinkingparticle** [comment]
Does it get solved if we update to 10.14 or 10.15?

**Comment by thinkingparticle** [comment]
Downgraded to versions below and now i dont get that error: 

trax                     1.3.6
tensorflow               2.1.0
tensorflow-addons        0.11.2
tensorflow-datasets      4.0.1
tensorflow-estimator     2.1.0
tensorflow-gan           2.0.0
tensorflow-hub           0.10.0
tensorflow-metadata      0.24.0
tensorflow-probability   0.7.0
tensorflow-text          2.0.1

**Comment by broken** [comment]
Is this still a problem? From the previous comment, it sounds like TF doesn't support the hardware, so I would argue we will not support anything they do not. At the moment, I feel there is nothing to do here, but feel free to let us know otherwise.


ps. After searching, I never found a bazel equivalent of CMAKE_OSX_DEPLOYMENT_TARGET; however, we do specify an older 10.9 OSX version when building the pip package - https://github.com/tensorflow/text/blob/master/oss_scripts/pip_package/build_pip_package.sh#L38.
