### ISSUE TITLE
Error: Could not retrieve ICU NFKC normalizer

### ISSUE THREAD

**Issue by Guitaricet** [tensorflow/text#38]
**System information**

  * Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
  * OS Platform and Distribution: MacOS 10.14.5
  * TensorFlow installed from (source or binary): binary
  * TensorFlow version: 2.0.0b0
  * Python version: Python 3.7.2
  * CUDA/cuDNN version: None
  * GPU model and memory: None

**Describe the current behavior**
Error on calling normalize_utf8

**Describe the expected behavior**
normalize_utf8 should not fail

**Code to reproduce the issue**
```python
import tensorflow as tf
import tensorflow_text as text
tf.enable_eager_execution()

print(text.normalize_utf8(['Äffin']))
```

**Error**

```python
/usr/local/lib/python3.7/site-packages/tensorflow_text/python/ops/normalize_ops.py in normalize_utf8(input, normalization_form, name)
     87       return input_tensor.with_flat_values(result)
     88     else:
---> 89       return gen_normalize_ops.normalize_utf8(input_tensor, normalization_form)

<string> in normalize_utf8(input, normalization_form, name)

/usr/local/lib/python3.7/site-packages/six.py in raise_from(value, from_value)

InternalError: U_FILE_ACCESS_ERROR: Could not retrieve ICU NFKC normalizer [Op:NormalizeUTF8]
```

**Comment by broken** [comment]
Yeah. This was fixed recently and should no longer be a problem with the next release we plan on pushing out soon.

**Comment by broken** [comment]
Builds with the normalizer's required data have been released.
