### ISSUE TITLE
How to generate test_oss_model.model file?

### ISSUE THREAD

**Issue by rposts** [tensorflow/text#394]
I am trying to test Tensorflow Serving on s390x architecture (big-endian) but running into testcase failures.  One of that has to do with `tesnorflow_text`.  I suspect in this instance, the problem occurs when [test_oss_model.model](https://github.com/tensorflow/text/blob/master/tensorflow_text/python/ops/test_data/test_oss_model.model) file is read on s390x architecture.  This model appears to be generated on x86 architecture.

In order to rule out endiness issue I need to generate `test_oss_model.model` file on s390x.  I looked at BUILD file but could not find anywhere how this file is being generated.  Can someone please point me to a place on how to generate this model?

Thanks.

**Comment by broken** [comment]
I believe it was created using the sample English corpus in the SP repo.

https://github.com/google/sentencepiece/blob/master/data/botchan.txt

spm_train --vocab_size=1000 --input=botchan.txt --model_prefix=m

**Comment by rposts** [comment]
@broken Thanks! I will try it out.

**Comment by rposts** [comment]
Closing. No further info needed at this point.  Thanks.
