### ISSUE TITLE
tensorflow-text installs tensorflow-cpu while tensorflow-gpu is already installed

### ISSUE THREAD

**Issue by hazemessamm** [tensorflow/text#416]
Every time I try to install tensorflow-text it installs TF-cpu and I think I don't need it because I have TF-gpu, so is there any way to avoid installing TF-cpu and also I don't know whether a conflict may happen between TF-cpu and TF-gpu or not.

**Comment by broken** [comment]
There is no conflict. This is because of the limitations of python packages. Please see https://github.com/tensorflow/text/issues/195 for more info. (I'm also going to mark this as a duplicate. If you have any info on a workaround for this problem, please reply on that thread.)
