### ISSUE TITLE
Excluding tf 2.5

### ISSUE THREAD

**Issue by JulesGM** [tensorflow/text#428]
Hello,
I use TF 2.5 in my project, and tf text is the only dependency that requires a lower version of Tensorflow.
Does Tensorflow 2.5 break Tensorflow text? If not, can you change the setup.py to let people who need tensorflow 2.5 use it.
Thanks.

**Comment by broken** [comment]
The ABI can change between TensorFlow minor versions. To prevent confusion, our libraries are built to work with the matching TF minor version. What this means is that TF Text 2.4.x is guaranteed to work with TF 2.4.x.

TF Text 2.4.x may also work with TF 2.5, but it is not guaranteed. If there were significant enough changes to the exported symbols in TF, this could cause problems.

You have two options.
1. Try it to see if it works. Pip install the latest version of tensorflow_text (2.4.0rc0 at the time of this writing), and then install the version of TF you want to try after.
2. Build a custom version of TF Text that works with TF 2.5.
