### ISSUE TITLE
`tensorflow_text.tools` not found on Google Colab

### ISSUE THREAD

**Issue by alexaorrico** [tensorflow/text#546]
I've been trying to import `tensorflow_text.tools` in Google Colab using the latest version of `tensorflow` (2.4.1) and it throws a `ModuleNotFound` error. It seems that there have been recent commits on the project to try and include `tools` in the `pip` package, but so far it doesn't seem to be included

**Comment by MarkDaoust** [comment]
Yes, I moved these into the pip package for this tutorial:

https://www.tensorflow.org/tutorials/tensorflow_text/subwords_tokenizer

The tutorial uses `tensorflow_text_nightly` which includes these recent changes.

They will be available in the next release of tensorflow_text, which will likely some shortly after the release of TensorFlow v2.5. We've started the release process for 2.5. So it will be a month or two before this is available in the stable version of `tensorflow_text`.

**Comment by Jamiil92** [comment]
Hi @MarkDaoust  
Please how do i resolve the issue ? I have been trying the above-mentioned tutorial and `import tensorflow_text as text` fails with the following error message. NotFoundError: /usr/local/lib/python3.7/dist-packages/tensorflow_text/python/metrics/_text_similarity_metric_ops.so: undefined symbol: _ZN10tensorflow15TensorShapeBaseINS_11TensorShapeEEC1EN4absl14lts_2020_02_254SpanIKxEE

Thanks

**Comment by MarkDaoust** [comment]
Thanks for the report @Jamiil92.

This error is because of a binary incompatibility between `tf-nightly` and `tf-text-nightly`.

It's probably been picked up by their internal testing and should be fixed (worst case) for the TF2.5 launch.

In the mean time I'm going to pin the nightly versions so this works in colab.

**Comment by Jamiil92** [comment]
> Thanks for the report @Jamiil92.
> 
> This error is because of a binary incompatibility between `tf-nightly` and `tf-text-nightly`.
> 
> It's probably been picked up by their internal testing and should be fixed (worst case) for the TF2.5 launch.
> 
> In the mean time I'm going to pin the nightly versions so this works in colab.

@MarkDaoust  the fix above has worked for a while but it has now broken again and `import tensorflow_text as text` fails with the same error message mentioned above.

Sorry for reopening this again :-(.

**Comment by 20v100** [comment]
Same Error for me as well.

I use docker on Ubuntu 18.04.5 LTS. I have tried the same packages than used in the above Colab tutorial in my Dockerfile:

```
RUN pip install tensorflow==2.4.1
RUN pip install tensorflow-text-nightly==2.5.0.dev20210325 
```

Error:
```
tensorflow.python.framework.errors_impl.NotFoundError: /usr/local/lib/python3.8/site-packages/tensorflow_text/python/metrics/_text_similarity_metric_ops.so: undefined symbol: _ZN10tensorflow15OpKernelContext15allocate_outputEN4absl14lts_2020_09_2311string_viewERKNS_11TensorShapeEPPNS_6TensorE
```

Thanks for you help!
