### ISSUE TITLE
CPU installation

### ISSUE THREAD

**Issue by numpde** [tensorflow/text#547]
I'm installing as follows:

```
python3 -m venv venv
source venv/bin/activate
pip install tensorflow-cpu==2.4.1
pip install tensorflow-text
```

But the last install also installs `tensorflow<2.5,>=2.4.0`, which I don't want. How can I stick to the CPU version?

**Comment by broken** [comment]
Install tensorflow-cpu again after installing tensorflow-text.

This is the same issue as #195 (though the default tensorflow has changed). Unfortunately, I do not believe there is a way to not uninstall tensorflow-cpu due to the limitations of pip, so you just need to manually install it again after.

**Comment by numpde** [comment]
Thanks @broken. Whenever 'there is no way', one must needs try.

With these requirements.txt:
```
tensorflow>=2.5.0rc0, <2.6
```
and constraints.txt:
```
tensorflow @ https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow_cpu-2.4.1-cp38-cp38-manylinux2010_x86_64.whl
```
installing with
```
pip install -r requirements.txt -c constraints.txt
```
seems to settle for the CPU version right away. Perhaps there is a more elegant way (i.e. url-free).

**Comment by broken** [comment]
Great! I'll keep this constraints trick in mind when asked this question in the future.

Ultimately, I would love for this to be automatic. So when anybody ran `pip install tensorflow-text`, it would ensure tensorflow or tensorflow-cpu is installed at the correct version and not require any manual intervention on the user side.

**Comment by buhrmann** [comment]
For future reference, the same trick seems to work also without a constraints file, since specifying a wheel location using `@` is a valid requirement spec. So you can simple have this in the `requirements.txt` file e.g.:
```
tensorflow @ https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow_cpu-2.5.0-cp38-cp38-manylinux2010_x86_64.whl 
tensorflow_text
```
