### ISSUE TITLE
Loaded runtime CuDNN library: 8.0.5 but source was compiled with: 8.1.0.

### ISSUE THREAD

**Issue by GiorgosFradelos** [tensorflow/text#554]
I was having trouble implementing any BERT model to my NLP project due to some tensorflow_text bug (tensorflow 2.4, same issue here: https://github.com/tensorflow/text/issues/476). After installing tf-models-nightly some changes were made under the hood and the error I am getting is: `Loaded runtime CuDNN library: 8.0.5 but source was compiled with: 8.1.0.`.  I just don't know what to do.

OS Windows10 
Python Version 3.8.0
Tensorflow Version:  2.6.0-dev20210407
Keras Version:  2.6.0

**Comment by broken** [comment]
It looks like you are using the nightly version of TF with a different stable version of TF Text (eg. 2.6.0-dev# w/ 2.4.x). You should switch to also using the nightly version of TF Text with the same version to ensure inoperability.

`pip install tensorflow-text-nightly==2.6.0-dev20210407`

**Comment by GiorgosFradelos** [comment]
I was using `cuDNN 8.0` for my initial installation of tensorflow 2.4 as it is mentioned here: https://www.tensorflow.org/install/source#gpu. Turns out that I had to download the `8.1.0 cuDNN` since tensorflow version changed to 2.6.0-dev20210407. It works fine now, thanks for the relpy.

**Comment by broken** [comment]
Great! I'm happy it's working for you.

**Comment by ddofer** [comment]
I have the same issue; downloading and installing cuDNN 8.1 (for CUDA 11) did NOT help. 

`2021-06-02 10:02:23.367252: W tensorflow/core/framework/op_kernel.cc:1767] OP_REQUIRES failed at cudnn_rnn_ops.cc:1553 : Unknown: Fail to find the dnn implementation.
2021-06-02 10:02:23.369234: E tensorflow/stream_executor/cuda/cuda_dnn.cc:352] Loaded runtime CuDNN library: 8.0.5 but source was compiled with: 8.1.0.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.
2021-06-02 10:02:23.370402: W tensorflow/core/framework/op_kernel.cc:1767] OP_REQUIRES failed at cudnn_rnn_ops.cc:1553 : Unknown: Fail to find the dnn implementation.`

**Comment by sauravsolanki** [comment]
This solve my problem [here](https://www.tensorflow.org/install/source#gpu). Try to match the verison.

**Comment by ai1361720220000** [comment]
> I was using `cuDNN 8.0` for my initial installation of tensorflow 2.4 as it is mentioned here: https://www.tensorflow.org/install/source#gpu. Turns out that I had to download the `8.1.0 cuDNN` since tensorflow version changed to 2.6.0-dev20210407. It works fine now, thanks for the relpy.

Hi, could you tell me how to find the suitable version of tensorflow for cuDNN8.1.0?? i can't find here https://www.tensorflow.org/install/source#gpu

**Comment by avinashnair02** [comment]
> This solve my problem [here](https://www.tensorflow.org/install/source#gpu). Try to match the verison.

Can you tell me how to do the same on google colab

**Comment by jamesbraza** [comment]
I was hitting this too, and here is how I solved.  From [How to verify CuDNN installation?](https://stackoverflow.com/q/31326015/11163122):

```bash
$ cat /usr/local/cuda/include/cudnn.h | grep CUDNN_MAJOR -A 2

#define CUDNN_MAJOR 7
#define CUDNN_MINOR 5
#define CUDNN_PATCHLEVEL 1
--
#define CUDNN_VERSION (CUDNN_MAJOR * 1000 + CUDNN_MINOR * 100 + CUDNN_PATCHLEVEL)

#include "driver_types.h"
```

We see this contains 7.5.1.  Unfortunately in https://www.tensorflow.org/install/source#gpu no minor version aligns.  I am not sure how I was getting an error that says 8.0.5, but from that printout I have 7.5.1 🤷 .

I sent it with `tensorflow<2.5` (actually installed `2.4.4`), and I even had to downgrade my repo's Python version from 3.10 to 3.8 to make this happen.

Luckily, this fixed my problem 🎉  , and hopefully this helps someone

**Comment by broken** [comment]
Thanks for sharing!

FYI, if anybody else is having a similar problem, please create a new issue and mention it is similar to this one rather than replying to this one. Nobody on our team monitors closed issues and your reply will most likely be lost and not responded to.

**Comment by Iksiboi777** [comment]
> > This solve my problem [here](https://www.tensorflow.org/install/source#gpu). Try to match the verison.
> 
> Can you tell me how to do the same on google colab

Can you help me with this as well?

**Comment by SnowyWhiteBeard** [comment]
> > > This solve my problem [here](https://www.tensorflow.org/install/source#gpu). Try to match the verison.
> > 
> > 
> > Can you tell me how to do the same on google colab
> 
> Can you help me with this as well?

I used `!dpkg -l libcudnn8*`  to check what version of cudnn on my Colab notebook. In my case, it was cudnn-8.0.5.
I used `!apt-cache policy libcudnn8` to see the versions of cudnn.
And finally I used `!apt install --allow-change-held-packages libcudnn8=8.1.0.77-1+cuda11.2`

Check again with `!dpkg -l libcudnn8*`

**Comment by NhutTien0905** [comment]
I have the same problem 
Window 10
Python Version 3.9.10
Tensorflow 2.9.1

**Comment by Poulinakis-Konstantinos** [comment]
I had a similar issue using a pretrained mobilenetv3 from tf-hub.
Linux Suse
Python Version 3.9.16
Tensorflow 2.11 & 2.9
I uninstalled cudnn and reinstalled cuDNN=8.1.  The problem persisted.

I had to downgrade to TensorFlow 2.4 with cuDNN=8.0

**Comment by JainRohan** [comment]
I have a similar issue: `Loaded runtime CuDNN library: 8.1.0 but source was compiled with: 8.2.4`.

Ubuntu 22.04
Python 3.10.6
Tensorflow 2.12.02

**Comment by hafedh-hichri** [comment]
i just followed the [tensorflow installation tutorial](https://www.tensorflow.org/install/pip) and it fixed it for me 
```
conda install -c conda-forge cudatoolkit=11.8.0 --y
python3 -m pip install nvidia-cudnn-cu11==8.6.0.163 tensorflow==2.12.*
mkdir -p $CONDA_PREFIX/etc/conda/activate.d
echo 'CUDNN_PATH=$(dirname $(python -c "import nvidia.cudnn;print(nvidia.cudnn.__file__)"))' >> $CONDA_PREFIX/etc/conda/activate.d/env_vars.sh
echo 'export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CONDA_PREFIX/lib/:$CUDNN_PATH/lib' >> $CONDA_PREFIX/etc/conda/activate.d/env_vars.sh
source $CONDA_PREFIX/etc/conda/activate.d/env_vars.sh
# Verify install:
python3 -c "import tensorflow as tf; print(tf.config.list_physical_devices('GPU'))"
```` 
```
conda install -c conda-forge cudatoolkit=11.8.0
pip install nvidia-cudnn-cu11==8.6.0.163
```
```
pip install --upgrade pip
```
```
pip install tensorflow==2.12.*
``` 
if you want to verify if everything is fixed or not use the following code 

```python
import tensorflow as tf
x = tf.random.uniform((8, 33, 558, 2), minval=-1, maxval=1)
conv = tf.keras.layers.Conv2D(2,(2,2))
conv(x).shape
``` 
note that using just `pip install tensorflow` does not install tensorflow and all of its dependencies.
let me know if this fixed your error

**Comment by mcdaqc** [comment]
> I have the same issue; downloading and installing cuDNN 8.1 (for CUDA 11) did NOT help.
> 
> `2021-06-02 10:02:23.367252: W tensorflow/core/framework/op_kernel.cc:1767] OP_REQUIRES failed at cudnn_rnn_ops.cc:1553 : Unknown: Fail to find the dnn implementation. 2021-06-02 10:02:23.369234: E tensorflow/stream_executor/cuda/cuda_dnn.cc:352] Loaded runtime CuDNN library: 8.0.5 but source was compiled with: 8.1.0. CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library. If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration. 2021-06-02 10:02:23.370402: W tensorflow/core/framework/op_kernel.cc:1767] OP_REQUIRES failed at cudnn_rnn_ops.cc:1553 : Unknown: Fail to find the dnn implementation.`

You have to restart the kernel

**Comment by m946107011** [comment]
Ubuntu 22.04
Python Python 3.8.10
Tensorflow 2.12.1


Loaded runtime CuDNN library: 8.0.5 but source was compiled with: 8.6.0.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.
2023-10-20 18:57:26.560643: W tensorflow/core/framework/op_kernel.cc:1828] OP_REQUIRES failed at xla_ops.cc:503 : FAILED_PRECONDITION: DNN library initialization failed. Look at the errors above for more details.


I try all the solution above but still not work

**Comment by Adipks** [comment]
I had encountered the same issue compiled with 8.6.0 and version present was 8.4.1 ,the solution was to download the appropriate CuDNN file from the nvidia website ,in your local computer and follow the installation instructions from the nvidiaCuDNN installation guide ,if you're using a docker simply copy the installed tar file into the docker and follow the installation steps.After completing the installation the error was resolved.

**Comment by chanangaza** [comment]
for me it was due to having 'cudnn' installed via conda. running `conda uninstall cudnn` resolved this.
