### ISSUE TITLE
Error when building from source

### ISSUE THREAD

**Issue by Zamen** [tensorflow/text#586]
Hi,

I am trying to build tensorflow-text from source with a built v2.5.0-rc3 of tensorflow (I want to use it with py39) on a Linux x86_64 machine. I followed the steps in the README but I get an error when building the pip package. Any clue?

`DEBUG: /home/ubuntu/.cache/bazel/_bazel_ubuntu/5873659843ee21afe39693f54dc2c4a7/external/org_tensorflow/third_party/repo.bzl:108:14:                                                    
Warning: skipping import of repository 'icu' because it already exists.                                                                                                                 
WARNING: /home/ubuntu/.cache/bazel/_bazel_ubuntu/5873659843ee21afe39693f54dc2c4a7/external/local_config_tf/BUILD:10:11: in linkstatic attribute of cc_library rule @local_config_tf//:li
btensorflow_framework: setting 'linkstatic=1' is recommended if there are no object files                                                                                               
ERROR: /home/ubuntu/.cache/bazel/_bazel_ubuntu/5873659843ee21afe39693f54dc2c4a7/external/com_google_protobuf/BUILD:981:21: in proto_lang_toolchain rule @com_google_protobuf//:cc_toolch
ain: '@com_google_protobuf//:cc_toolchain' does not have mandatory provider 'ProtoInfo'.                                                                                                
ERROR: Analysis of target '//oss_scripts/pip_package:build_pip_package' failed; build aborted: Analysis of target '@com_google_protobuf//:cc_toolchain' failed                          
INFO: Elapsed time: 10.324s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (8 packages loaded, 207 targets configured)
`

**Comment by broken** [comment]
FYI; we have 3.9 targets in our nightly release (tensorflow-text-nightly), and should have it with the 2.5 release later this week.

Regarding the error, I'm not sure. Could it be that 2.5.0-rc3 of TF has a different version of protobuf than we have defined in the WORKSPACE file? I don't think we have seen this with our builds though. This may take some back & forth, do either of the two options above work for you (nightly or wait a couple days)?

**Comment by Stonepia** [comment]
@broken  I get the same error when building from latest master branch of TF (2.6.0). I found that in your WORKSPACE file only set the tensorflow verion 2.5, so that is this the reason that lead to the error?

Since the TF does not release v2.6 currently, so that I cannot change the url like " "https://github.com/tensorflow/tensorflow/archive/v2.5.0-rc0.zip" , how could I change the WORKSPACE file to support this?

**Comment by Stonepia** [comment]
@broken  I recompiled tensorflow at r2.5 branch today, it still get the same error. For your instance, I list my information below:

OS: ubuntu 20.04
CUDA version : 11.3 
CuDNN version : 8.1.1
Tensorflow version: r2.5, build from source

Text branch : master branch at 689a0e956014ab142f809fb3a37b48d05c9a4a23.


```Batch
DEBUG: /home/user/.cache/bazel/_bazel_user/72b873eb6d5ae04e4604623b233589ea/external/org_tensorflow/third_party/repo.bzl:108:14:
Warning: skipping import of repository 'icu' because it already exists.
DEBUG: Rule 'io_bazel_rules_docker' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1556410077 -0400"
DEBUG: Repository io_bazel_rules_docker instantiated at:
  /home/user/text/WORKSPACE:78:10: in <toplevel>
  /home/user/.cache/bazel/_bazel_user/72b873eb6d5ae04e4604623b233589ea/external/org_tensorflow/tensorflow/workspace0.bzl:105:34: in workspace
  /home/user/.cache/bazel/_bazel_user/72b873eb6d5ae04e4604623b233589ea/external/bazel_toolchains/repositories/repositories.bzl:37:23: in repositories
Repository rule git_repository defined at:
  /home/user/.cache/bazel/_bazel_user/72b873eb6d5ae04e4604623b233589ea/external/bazel_tools/tools/build_defs/repo/git.bzl:199:33: in <toplevel>
WARNING: /home/user/.cache/bazel/_bazel_user/72b873eb6d5ae04e4604623b233589ea/external/local_config_tf/BUILD:10:11: in linkstatic attribute of cc_library rule @local_config_tf//:libtensorflow_framework: setting 'linkstatic=1' is recommended if there are no object files
ERROR: /home/user/.cache/bazel/_bazel_user/72b873eb6d5ae04e4604623b233589ea/external/com_google_protobuf/BUILD:981:21: in proto_lang_toolchain rule @com_google_protobuf//:cc_toolchain: '@com_google_protobuf//:cc_toolchain' does not have mandatory provider 'ProtoInfo'.
INFO: Repository icu instantiated at:
  /home/user/text/WORKSPACE:16:13: in <toplevel>
Repository rule http_archive defined at:
  /home/user/.cache/bazel/_bazel_user/72b873eb6d5ae04e4604623b233589ea/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
ERROR: Analysis of target '//oss_scripts/pip_package:build_pip_package' failed; build aborted: Analysis of target '@com_google_protobuf//:cc_toolchain' failed
INFO: Elapsed time: 59.161s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (56 packages loaded, 1404 targets configured)
```

I searched for the information, it is about [this](https://github.com/bazelbuild/bazel/issues/11694). However, I am not familiar with the bazel build tool, could you please point out where should I fix this?

**Comment by Stonepia** [comment]
Since this is the problem with the bazel version, so use bazel 3.7.2 instead of 4.0.0 could be a tempo solution.

**Comment by broken** [comment]
Yes, we currently use bazel 3.7.2. Did that fix your problem?

**Comment by Stonepia** [comment]
> Yes, we currently use bazel 3.7.2. Did that fix your problem? 

For me, 3.7.2 could successfully build.

**Comment by broken** [comment]
Great!
