### ISSUE TITLE
tensorflow-text crashes in google colab

### ISSUE THREAD

**Issue by kpe** [tensorflow/text#61]
When executed in Google Colab, this code crashes the session:
```
!pip install tensorflow_text

import tensorflow as tf
import tensorflow_text as text

docs = tf.data.Dataset.from_tensor_slices([['Never tell me the odds.'], ["It's a trap!"]])
tokenizer = text.WhitespaceTokenizer()
tokenized_docs = docs.map(lambda x: tokenizer.tokenize(x))
iterator = tokenized_docs.make_one_shot_iterator()
print(iterator.get_next().to_list())
```

It also SegFaults when executed locally.

**Comment by broken** [comment]
This is odd, our code didn't change (this still works with the previous version 1.0.0b0) and it works outside of tf.data, so it may a strange interaction with the new beta of tf. I'm looking into it.

**Comment by kpe** [comment]
after applying this patch (to build locally against a locally built TF 2.0.0b1) and explicitly calling `tf.enable_eager_execution()` (a thought this should be by default now), it worked without a crash:
```diff
diff --git a/third_party/tensorflow/BUILD.tpl b/third_party/tensorflow/BUILD.tpl
index 47b5aac..6910dbd 100644
--- a/third_party/tensorflow/BUILD.tpl
+++ b/third_party/tensorflow/BUILD.tpl
@@ -9,8 +9,8 @@ cc_library(
 
 cc_library(
     name = "libtensorflow_framework",
-    srcs = [":libtensorflow_framework.so.1"],
-    #data = ["lib/libtensorflow_framework.so.1"],
+    srcs = [":libtensorflow_framework.so.2"],
+    #data = ["lib/libtensorflow_framework.so.2"],
     visibility = ["//visibility:public"],
 )
 
diff --git a/third_party/tensorflow/tf_configure.bzl b/third_party/tensorflow/tf_configure.bzl
index 4e1ec8a..d3b62ee 100644
--- a/third_party/tensorflow/tf_configure.bzl
+++ b/third_party/tensorflow/tf_configure.bzl
@@ -186,14 +186,14 @@ def _tf_pip_impl(repository_ctx):
     )
 
     tf_shared_library_dir = repository_ctx.os.environ[_TF_SHARED_LIBRARY_DIR]
-    tf_shared_library_path = "%s/libtensorflow_framework.so.1" % tf_shared_library_dir
+    tf_shared_library_path = "%s/libtensorflow_framework.so.2" % tf_shared_library_dir
     tf_shared_library_rule = _symlink_genrule_for_dir(
         repository_ctx,
         None,
         "",
-        "libtensorflow_framework.so.1",
+        "libtensorflow_framework.so.2",
         [tf_shared_library_path],
-        ["libtensorflow_framework.so.1"],
+        ["libtensorflow_framework.so.2"],
     )
 
     _tpl(repository_ctx, "BUILD", {

```

**Comment by kpe** [comment]
When I use the pypi tensorflow-2.0.0.b1 version (i.e. not the locally build one), and the locally build TF-Text, I'm getting this:
```
 $ python crash.py 
Traceback (most recent call last):
  File "crash.py", line 2, in <module>
    import tensorflow_text as text
  File "/home/kpe/proj/local/bert-for-tf2/.venv/lib64/python3.6/site-packages/tensorflow_text/__init__.py", line 20, in <module>
    from tensorflow_text.python.ops import *
  File "/home/kpe/proj/local/bert-for-tf2/.venv/lib64/python3.6/site-packages/tensorflow_text/python/ops/__init__.py", line 19, in <module>
    from tensorflow_text.python.ops.greedy_constrained_sequence_op import greedy_constrained_sequence
  File "/home/kpe/proj/local/bert-for-tf2/.venv/lib64/python3.6/site-packages/tensorflow_text/python/ops/greedy_constrained_sequence_op.py", line 34, in <module>
    gen_constrained_sequence_op = load_library.load_op_library(resource_loader.get_path_to_datafile('_constrained_sequence_op.so'))
  File "/home/kpe/proj/local/bert-for-tf2/.venv/lib64/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /home/kpe/proj/local/bert-for-tf2/.venv/lib64/python3.6/site-packages/tensorflow_text/python/ops/_constrained_sequence_op.so: undefined symbol: _ZN10tensorflow7strings6StrCatB5cxx11ERKNS0_8AlphaNumES3_

```

**Comment by broken** [comment]
Were you building TF from head? The fact that tf.enable_eager_execution() is required makes me think you were building the recent 1.x release (1.14).  This bug only occurs to happen with TF 2.0.0-beta1, and not at HEAD, so I believe something got cherry-picked in, but another necessary change was left out. The segfault is occurring when creating the custom tokenizer op (File ".../tensorflow/python/framework/ops.py", line 1551 in _create_c_op). I've reached out to the core TF team to take a look.

wrt the patch, I have pr #63 that should fix this. Our recent release was built with .2, but erroneously the first 2.0 beta for TF wrote out to .1, so there was some hard-coding that had to be put in.

wrt locally building, you need to build TF also if you build tf.Text locally or the ABI versions are probably mismatched. Another option would be to build the package in a docker image - quay.io/pypa/manylinux2010_x86_64 or our testing image should also work (tensorflow/tf-text:gcp-unittest).

**Comment by broken** [comment]
Turns out this was ABI problem, where are binaries were built on the manylinux, and TF was on ubuntu 4.8 (the same as our testing docker image). I've kicked off new builds and should be able to publish a new release today or tomorrow that will fix this. Thanks for catching it.

**Comment by kpe** [comment]
OK, thank you! 
(Probably not relevant now, but I believe my locally build TF was from the r2.0 branch, so it's quite possible that for whatever reason eager_execution was not the default there, at the time when it was built). Anyway, once the new build is there, I'll give it a try! Thanks!

**Comment by broken** [comment]
FYI, new builds have been released.

**Comment by kpe** [comment]
thank you, works just fine in colab now!
