### ISSUE TITLE
Is there any way to handle / preserve SPECIAL tokens .

### ISSUE THREAD

**Issue by s4sarath** [tensorflow/text#656]
Hi , I was trying to do some MASKING-based experiments.
But, what happens is that special tokens like [MASK] are getting split into further pieces.

Is the following possible.

```
text = 'this is [MASK] token with [SEP]'
tokenizer.tokenize(text)

Output:

['▁this', '▁is', '[MASK]', '▁to', 'ken', '▁with', '[SEP]']

```

Thanks.

**Comment by broken** [comment]
Normally you tokenize before masking. We have a guide for masked language model preprocessing on tensorflow.org. https://www.tensorflow.org/text/guide/bert_preprocessing_guide

I strongly suggest taking a look there first. Otherwise, you would need use the WhitespaceTokenizer first, and then use SentencepieceTokenizer's stringToId method (which looks up the ID from the vocab for a given token) followed by tokenize for those words that it did not find an ID for.

**Comment by s4sarath** [comment]
I agree with your Robert. Normally yes, we tokenize before MASKING.
But, I was actually planning to do a MASK filling task.

For eg:
predict the mask token.
What happens, if I do masking after tokenizing, there is no guarantee that I might be properly masking a "full word". It might be  a part of the subword.

```
text = 'I want to buy the car because it is cheap'
# Let's say I have to mask "car"
text = 'I want to buy the [MASK] because it is cheap'
```
Here masking after tokenizing might not be apt.

Regarding string_to_id, it still has issues. A sample example

```
text = 'This is [MASK] token with [CLS] </s>'
tokenizer_sp.string_to_id(text.split())
# output
[ 3713,   159, 32001,     2,  4065, 32000,     1]

# But the actual output is
tokenizer_sp.string_to_id(['▁This', '▁is', '[MASK]', '▁token', '▁with', '[CLS]', '</s>'])
[  100,    19, 32001, 14145,    28, 32000,     1]
```
But I think it's okay. it's not a very common case. Huggingface tokenizer does that and its easy to do in python. But using tf text or tf ops its little difficult for me.

**Comment by broken** [comment]
I didn't notice you were using Sentencepiece initially, but if you create your vocab with the control symbols; it is my understanding that it will not tokenize them. See https://github.com/google/sentencepiece/issues/306

wrt masking the full word:
If you use BertTokenizer (or WhitespaceTokenizer & WordpieceTokenizer) as your subword tokenizer instead, you get tokens grouped by words in a ragged tensor (eg. [['I'], ['wa', '##nt'], ['to'], ['bu', '##y'], ...]). The guide calls merge_dims after which removes the word grouping, but if you skip this, you can then use the Selector and Mask in the guide as shown and it will mask by word instead.

**Comment by s4sarath** [comment]
Regarding wordpiece it's a beautiful tip. Thanks Robert. I will try that. 

And to be frank, I don't find a reason to Sentencepiece for english, it makes life very difficult at many places.
 
Isn't it **user defined symbols** that won't break into pieces right ? Or is it **control symbols**. I will build a small sentencepiece and check.

**Comment by broken** [comment]
You're correct. I meant 'user defined symbols'.
