### ISSUE TITLE
Doubt in the transformer tutorial

### ISSUE THREAD

**Issue by microcoder-py** [tensorflow/text#665]
The decoder embedding layer needs positive integers for encoding, but I see no step at which we are translating the output into such a format. How is the decoder embedding layer able to accept the encoder outputs then?

**Comment by broken** [comment]
Thanks; we'll take a look.

**Comment by MarkDaoust** [comment]
It's these tokenizer objects that convert the the text to lists of integers, and vice-versa:

https://www.tensorflow.org/text/tutorials/transformer#text_tokenization_detokenization

Does that answer your question?

**Comment by microcoder-py** [comment]
Hi, thank you for your responses. I actually went through the whole thing again, I was wrong. For teacher forcing you’re making use of the sentence embeddings for the target sequence, the output of encoder then is irrelevant. The model works fine
