### ISSUE TITLE
WordpieceTokenizer vocab_lookup_table initialization

### ISSUE THREAD

**Issue by EternalMoment** [tensorflow/text#70]
Hey team,

How could I initialize a `vocab_lookup_table` in `WordpieceTokenizer`. It would be great to add this into the current documentation. Thanks!

**Comment by thuang513** [comment]
A vocab table can be created using tf.lookup.StaticVocabulary table. here is an example:

`def _create_table(vocab_tensor, num_oov_buckets=1):
  init = tf.lookup.KeyValueTensorInitializer(
      vocab_tensor,
      tf.range(tf.size(vocab, out_type=tf.int64), dtype=tf.int64),
      key_dtype=tf.string,
      value_dtype=tf.int64)
  return tf.lookup.StaticVocabularyTable(
      init, num_oov, lookup_key_dtype=tf.string)`

See [1] for more details on StaticVocabularyTable.

[1] https://www.tensorflow.org/api_docs/python/tf/lookup/StaticVocabularyTable
