### ISSUE TITLE
Potential optimization for LongestMatchStartingAt in WordpieceTokenizer?

### ISSUE THREAD

**Issue by matthen** [tensorflow/text#71]
Currently the code uses a maximum word length, and refuses to tokenize longer words. The `LongestMatchStartingAt` helper function considers all string prefixes starting with the entire word.

If we instead passed the maximum subtoken length, then perhaps `LongestMatchStartingAt` could consider prefixes of at most that length. This could speed up this function and might mean we don't need to set a maximum word length.

Sorry if I have misunderstood something!

**Comment by broken** [comment]
This would work, but I don't think we would want to make the change. Wordpiece is built to split token/words into subwords, thus reducing the needed vocabulary size. One of the reasons to cap the max size of the words is that we don't expect valid tokens to be that long. Any word/token that is over that length, we expect it to not be valid and is thus safe to ignore and not waste resources on trying to break it further into subwords. I think if we cared about these tokens, your approach would be better.

**Comment by broken** [comment]
I'm going to close this, but feel free to reopen if you had a question or believe I over-looked something.

**Comment by matthen** [comment]
1. this optimization would work in tandem with the max word size. the current code wastes cycles checking the vocabulary for substrings that are too long to be present
2. wordpiece is also useful to tokenize languages that don't use spaces, or have any way to do an initial split into word tokens. In this case the user would set a very large max word length, and then this optimization would help keep it efficient
3. this is the method used in tensor2tensor, and it would help users switch over from that code https://github.com/tensorflow/tensor2tensor/blob/89f12fe9b45e9d5f30e97407407f1e277e37a031/tensor2tensor/data_generators/text_encoder.py#L616

i'm happy to send a PR that adds a max subtoken length flag, defaulting to None meaning no known max.

**Comment by broken** [comment]
Got it. I read your original comment too quick and misunderstood your proposal, but I think it could help. We would be happy to accept a PR.

wrt (2), I had also thought of possibly using wordpiece for cjkt languages, but haven't actually tested or heard about attempts to use it. I would be interested to know how well that could perform against simple character splitting. It could break characters that would be generally paired, but if the length was long enough it might not matter as much.

**Comment by matthen** [comment]
Cool I will send a PR soon.

this algorithm is a common baseline for cjkt, referred to as 'greedy' or 'maximum matching' tokenization. e.g. it is used as a baseline in https://aclweb.org/anthology/papers/O/O03/O03-4002/ I think it is a pretty solid baseline for chinese.
