### ISSUE TITLE
wordpiece detokenization

### ISSUE THREAD

**Issue by EternalMoment** [tensorflow/text#76]
Hey team, 

is it possible to detokenize wordpieces with tf text? If not, is this feature something that you would consider implementing in the future?

**Comment by broken** [comment]
Yeah; detokenizing wordpiece is deterministic and we've talked about adding it. I bring it up again with the team and see if somebody has some time to add it.

**Comment by broken** [comment]
FYI; we recently added Sentencepiece which is similar to Wordpiece and includes a detokenize method.

**Comment by EternalMoment** [comment]
@broken hey thanks for the new feature! 
This would be great for using XLNet and ALBERT, but in order to run BERT in production setting, wordpiece would be helpful.

**Comment by NeelGhoshal** [comment]
Hello,
I was wondering if I could help in any way regarding this issue?
I am relatively new to contributing and wanted to find some issues to work on here.

**Comment by broken** [comment]
We would happily accept assistance! We actually have this added already (https://www.tensorflow.org/text/api_docs/python/text/WordpieceTokenizer#detokenize), we just forgot to close out this issue.

If you are looking to help apart from this issue, one to start could be https://github.com/tensorflow/text/issues/583

**Comment by NeelGhoshal** [comment]
Thanks for your response @broken , I will check it out
