### ISSUE TITLE
Byte Level BPE Tokenizer (GPT2/RoBERTa )

### ISSUE THREAD

**Issue by sinamoeini** [tensorflow/text#763]
Hi TensorFlow team,

Is there going to be a byte level bpe tokenizer in tensorflow text?

**Comment by thuang513** [comment]
BPE is already supported by [SentencePiece](https://github.com/google/sentencepiece). If you have a sentence piece model, you can use it with the sentencepiece op.

**Comment by sinamoeini** [comment]
Thank you @thuang513. So sentencepiece and **byte-level** BPE only differ in training phase, right? So if I have a trained byte-level BPE I should be able to use sentencepiece and just give it the vocab and merges.

**Comment by thuang513** [comment]
I believe so. If you trained the model using SentencePiece you should be able to use it as is.

**Comment by sinamoeini** [comment]
I dug a bit more and it seems that there is a small difference in how they treat spaces. I will try to replicate hugging face RoBERTa tokenizer using tensorflow sentence piece tokenizer and update this thread

**Comment by MarkusSagen** [comment]
@sinamoeini Any updates on this?
