### ISSUE TITLE
python(28903,0x117a3e600) malloc: *** error for object 0x519e4148712e0070: pointer being freed was not allocated

### ISSUE THREAD

**Issue by dbl001** [tensorflow/text#796]
On OS X 12.1 with Python 3.8.5 in an Anaconda virtual environment with Tensorflow 2.5.0:
```
% conda list tensorflow
# packages in environment at /Users/davidlaxer/anaconda3/envs/ai:
#
# Name                    Version                   Build  Channel
tensorflow                2.5.0                    pypi_0    pypi
tensorflow-addons         0.14.0                   pypi_0    pypi
tensorflow-datasets       4.3.0                    pypi_0    pypi
tensorflow-estimator      2.5.0                    pypi_0    pypi
tensorflow-hub            0.12.0                   pypi_0    pypi
tensorflow-io-gcs-filesystem 0.21.0                   pypi_0    pypi
tensorflow-metadata       1.0.0                    pypi_0    pypi
tensorflow-probability    0.13.0rc0                pypi_0    pypi
tensorflow-text           2.5.0                    pypi_0    pypi

% ipython
Python 3.8.5 (default, Sep  4 2020, 02:22:02) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.18.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import tensorflow_text
python(28903,0x117a3e600) malloc: *** error for object 0x519e4148712e0070: pointer being freed was not allocated
python(28903,0x117a3e600) malloc: *** set a breakpoint in malloc_error_break to debug
zsh: abort      ipython

% ipython              
Python 3.8.5 (default, Sep  4 2020, 02:22:02) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.18.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import tensorflow

In [2]: print (tensorflow.__version__)
2.5.0

In [3]: import tensorflow_text
python(30643,0x10ed58600) malloc: *** error for object 0x28f18b689739001f: pointer being freed was not allocated
python(30643,0x10ed58600) malloc: *** set a breakpoint in malloc_error_break to debug
zsh: abort      ipython


```

**Comment by broken** [comment]
Can you take a look at #644? I suspect something similar is going on here.

**Comment by dbl001** [comment]
I upgraded to tensorflow 2.7.0 and tensorflow_text 2.7.0 and now I am getting:
```
% ipython
Python 3.8.5 (default, Sep  4 2020, 02:22:02) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.18.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import tensorflow_text
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-4dd33f1b1ed3> in <module>
----> 1 import tensorflow_text

~/anaconda3/envs/ai/lib/python3.8/site-packages/tensorflow_text/__init__.py in <module>
     18 
     19 # pylint: disable=wildcard-import
---> 20 from tensorflow_text.core.pybinds import tflite_registrar
     21 from tensorflow_text.python import keras
     22 from tensorflow_text.python import metrics

ModuleNotFoundError: No module named 'tensorflow_text.core'

In [2]: quit()
(ai) davidlaxer@x86_64-apple-darwin13 Top2Vec % conda list tensorflow_text
# packages in environment at /Users/davidlaxer/anaconda3/envs/ai:
#
# Name                    Version                   Build  Channel
(ai) davidlaxer@x86_64-apple-darwin13 Top2Vec % conda list tensorflow
# packages in environment at /Users/davidlaxer/anaconda3/envs/ai:
#
# Name                    Version                   Build  Channel
tensorflow                2.7.0                    pypi_0    pypi
tensorflow-addons         0.14.0                   pypi_0    pypi
tensorflow-datasets       4.3.0                    pypi_0    pypi
tensorflow-estimator      2.7.0                    pypi_0    pypi
tensorflow-hub            0.12.0                   pypi_0    pypi
tensorflow-io-gcs-filesystem 0.21.0                   pypi_0    pypi
tensorflow-metadata       1.0.0                    pypi_0    pypi
tensorflow-probability    0.15.0                   pypi_0    pypi
tensorflow-text           2.7.0                    pypi_0    pypi
```

**Comment by broken** [comment]
There was a problem with the 2.7.0 osx builds (I should remove them). Please use the more recent 2.7.3.

**Comment by dbl001** [comment]
% pip install tensorflow-text==2.7.3
Collecting tensorflow-text==2.7.3
  Downloading tensorflow_text-2.7.3-cp38-cp38-macosx_10_9_x86_64.whl (4.0 MB)
     |████████████████████████████████| 4.0 MB 1.4 MB/s            
Requirement already satisfied: tensorflow<2.8,>=2.7.0 in /Users/davidlaxer/anaconda3/envs/ai/lib/python3.8/site-packages (from tensorflow-text==2.7.3) (2.7.0)
Requirement already satisfied: tensorflow-hub>=0.8.0 in /Users/davidlaxer/anaconda3/envs/ai/lib/python3.8/site-packages (from tensorflow-text==2.7.3) (0.12.0)
Requirement already satisfied: termcolor>=1.1.0 in /Users/davidlaxer/anaconda3/envs/ai/lib/python3.8/site-packages (from tensorflow<2.8,>=2.7.0->tensorflow-text==2.7.3) (1.1.0)
Requirement already satisfied: tensorboard~=2.6 in /Users/davidlaxer/anaconda3/envs/ai/lib/python3.8/site-packages (from tensorflow<2.8,>=2.7.0->tensorflow-text==2.7.3) (2.6.0)
Requirement already satisfied: libclang>=9.0.1 in /Users/davidlaxer/anaconda3/envs/ai/lib/python3.8/site-packages (from tensorflow<2.8,>=2.7.0->tensorflow-text==2.7.3) (11.1.0)
Requirement already satisfied: gast<0.5.0,>=0.2.1 in /Users/davidlaxer/anaconda3/envs/ai/lib/python3.8/site-packages (from tensorflow<2.8,>=2.7.0->tensorflow-text==2.7.3) (0.4.0)
Requirement already satisfied: tensorflow-estimator<2.8,~=2.7.0rc0 in /Users/davidlaxer/anaconda3/envs/ai/lib/python3.8/site-packages (from tensorflow<2.8,>=2.7.0->tensorflow-text==2.7.3) (2.7.0)
Requirement already satisfied: h5py>=2.9.0 in /Users/davidlaxer/anaconda3/envs/ai/lib/python3.8/site-packages (from tensorflow<2.8,>=2.7.0->tensorflow-text==2.7.3) (3.1.0)
Requirement already satisfied: six>=1.12.0 in /Users/davidlaxer/anaconda3/envs/ai/lib/python3.8/site-packages (from tensorflow<2.8,>=2.7.0->tensorflow-text==2.7.3) (1.15.0)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.21.0 in /Users/davidlaxer/anaconda3/envs/ai/lib/python3.8/site-packages (from tensorflow<2.8,>=2.7.0->tensorflow-text==2.7.3) (0.21.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /Users/davidlaxer/anaconda3/envs/ai/lib/python3.8/site-packages (from tensorflow<2.8,>=2.7.0->tensorflow-text==2.7.3) (3.7.4.3)
Requirement already satisfied: absl-py>=0.4.0 in /Users/davidlaxer/anaconda3/envs/ai/lib/python3.8/site-packages (from tensorflow<2.8,>=2.7.0->tensorflow-text==2.7.3) (0.12.0)
Requirement already satisfied: protobuf>=3.9.2 in /Users/davidlaxer/anaconda3/envs/ai/lib/python3.8/site-packages (from tensorflow<2.8,>=2.7.0->tensorflow-text==2.7.3) (3.17.1)
Requirement already satisfied: numpy>=1.14.5 in /Users/davidlaxer/anaconda3/envs/ai/lib/python3.8/site-packages (from tensorflow<2.8,>=2.7.0->tensorflow-text==2.7.3) (1.20.0)
Requirement already satisfied: astunparse>=1.6.0 in /Users/davidlaxer/anaconda3/envs/ai/lib/python3.8/site-packages (from tensorflow<2.8,>=2.7.0->tensorflow-text==2.7.3) (1.6.3)
Requirement already satisfied: opt-einsum>=2.3.2 in /Users/davidlaxer/anaconda3/envs/ai/lib/python3.8/site-packages (from tensorflow<2.8,>=2.7.0->tensorflow-text==2.7.3) (3.3.0)
Requirement already satisfied: wrapt>=1.11.0 in /Users/davidlaxer/anaconda3/envs/ai/lib/python3.8/site-packages (from tensorflow<2.8,>=2.7.0->tensorflow-text==2.7.3) (1.12.1)
Requirement already satisfied: keras<2.8,>=2.7.0rc0 in /Users/davidlaxer/anaconda3/envs/ai/lib/python3.8/site-packages (from tensorflow<2.8,>=2.7.0->tensorflow-text==2.7.3) (2.7.0)
Requirement already satisfied: wheel<1.0,>=0.32.0 in /Users/davidlaxer/anaconda3/envs/ai/lib/python3.8/site-packages (from tensorflow<2.8,>=2.7.0->tensorflow-text==2.7.3) (0.37.0)
Requirement already satisfied: google-pasta>=0.1.1 in /Users/davidlaxer/anaconda3/envs/ai/lib/python3.8/site-packages (from tensorflow<2.8,>=2.7.0->tensorflow-text==2.7.3) (0.2.0)
Requirement already satisfied: keras-preprocessing>=1.1.1 in /Users/davidlaxer/anaconda3/envs/ai/lib/python3.8/site-packages (from tensorflow<2.8,>=2.7.0->tensorflow-text==2.7.3) (1.1.2)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /Users/davidlaxer/anaconda3/envs/ai/lib/python3.8/site-packages (from tensorflow<2.8,>=2.7.0->tensorflow-text==2.7.3) (1.34.1)
Requirement already satisfied: flatbuffers<3.0,>=1.12 in /Users/davidlaxer/anaconda3/envs/ai/lib/python3.8/site-packages (from tensorflow<2.8,>=2.7.0->tensorflow-text==2.7.3) (1.12)
Requirement already satisfied: werkzeug>=0.11.15 in /Users/davidlaxer/anaconda3/envs/ai/lib/python3.8/site-packages (from tensorboard~=2.6->tensorflow<2.8,>=2.7.0->tensorflow-text==2.7.3) (2.0.1)
Requirement already satisfied: tensorboard-data-server<0.7.0,>=0.6.0 in /Users/davidlaxer/anaconda3/envs/ai/lib/python3.8/site-packages (from tensorboard~=2.6->tensorflow<2.8,>=2.7.0->tensorflow-text==2.7.3) (0.6.1)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in /Users/davidlaxer/anaconda3/envs/ai/lib/python3.8/site-packages (from tensorboard~=2.6->tensorflow<2.8,>=2.7.0->tensorflow-text==2.7.3) (1.8.0)
Requirement already satisfied: setuptools>=41.0.0 in /Users/davidlaxer/anaconda3/envs/ai/lib/python3.8/site-packages (from tensorboard~=2.6->tensorflow<2.8,>=2.7.0->tensorflow-text==2.7.3) (50.3.0.post20201006)
Requirement already satisfied: google-auth<2,>=1.6.3 in /Users/davidlaxer/anaconda3/envs/ai/lib/python3.8/site-packages (from tensorboard~=2.6->tensorflow<2.8,>=2.7.0->tensorflow-text==2.7.3) (1.30.1)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in /Users/davidlaxer/anaconda3/envs/ai/lib/python3.8/site-packages (from tensorboard~=2.6->tensorflow<2.8,>=2.7.0->tensorflow-text==2.7.3) (0.4.4)
Requirement already satisfied: markdown>=2.6.8 in /Users/davidlaxer/anaconda3/envs/ai/lib/python3.8/site-packages (from tensorboard~=2.6->tensorflow<2.8,>=2.7.0->tensorflow-text==2.7.3) (3.3.4)
Requirement already satisfied: requests<3,>=2.21.0 in /Users/davidlaxer/anaconda3/envs/ai/lib/python3.8/site-packages (from tensorboard~=2.6->tensorflow<2.8,>=2.7.0->tensorflow-text==2.7.3) (2.25.1)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /Users/davidlaxer/anaconda3/envs/ai/lib/python3.8/site-packages (from google-auth<2,>=1.6.3->tensorboard~=2.6->tensorflow<2.8,>=2.7.0->tensorflow-text==2.7.3) (0.2.8)
Requirement already satisfied: cachetools<5.0,>=2.0.0 in /Users/davidlaxer/anaconda3/envs/ai/lib/python3.8/site-packages (from google-auth<2,>=1.6.3->tensorboard~=2.6->tensorflow<2.8,>=2.7.0->tensorflow-text==2.7.3) (4.2.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /Users/davidlaxer/anaconda3/envs/ai/lib/python3.8/site-packages (from google-auth<2,>=1.6.3->tensorboard~=2.6->tensorflow<2.8,>=2.7.0->tensorflow-text==2.7.3) (4.7.2)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /Users/davidlaxer/anaconda3/envs/ai/lib/python3.8/site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard~=2.6->tensorflow<2.8,>=2.7.0->tensorflow-text==2.7.3) (1.3.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Users/davidlaxer/anaconda3/envs/ai/lib/python3.8/site-packages (from requests<3,>=2.21.0->tensorboard~=2.6->tensorflow<2.8,>=2.7.0->tensorflow-text==2.7.3) (1.26.5)
Requirement already satisfied: certifi>=2017.4.17 in /Users/davidlaxer/anaconda3/envs/ai/lib/python3.8/site-packages (from requests<3,>=2.21.0->tensorboard~=2.6->tensorflow<2.8,>=2.7.0->tensorflow-text==2.7.3) (2020.6.20)
Requirement already satisfied: idna<3,>=2.5 in /Users/davidlaxer/anaconda3/envs/ai/lib/python3.8/site-packages (from requests<3,>=2.21.0->tensorboard~=2.6->tensorflow<2.8,>=2.7.0->tensorflow-text==2.7.3) (2.10)
Requirement already satisfied: chardet<5,>=3.0.2 in /Users/davidlaxer/anaconda3/envs/ai/lib/python3.8/site-packages (from requests<3,>=2.21.0->tensorboard~=2.6->tensorflow<2.8,>=2.7.0->tensorflow-text==2.7.3) (4.0.0)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /Users/davidlaxer/anaconda3/envs/ai/lib/python3.8/site-packages (from pyasn1-modules>=0.2.1->google-auth<2,>=1.6.3->tensorboard~=2.6->tensorflow<2.8,>=2.7.0->tensorflow-text==2.7.3) (0.4.8)
Requirement already satisfied: oauthlib>=3.0.0 in /Users/davidlaxer/anaconda3/envs/ai/lib/python3.8/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard~=2.6->tensorflow<2.8,>=2.7.0->tensorflow-text==2.7.3) (3.1.0)
Installing collected packages: tensorflow-text
  Attempting uninstall: tensorflow-text
    Found existing installation: tensorflow-text 2.7.0
    Uninstalling tensorflow-text-2.7.0:
      Successfully uninstalled tensorflow-text-2.7.0
Successfully installed tensorflow-text-2.7.3
(ai) davidlaxer@x86_64-apple-darwin13 Top2Vec % ipython
Python 3.8.5 (default, Sep  4 2020, 02:22:02) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.18.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import tensorflow_text

In [2]: quit()

**Comment by paullintilhac** [comment]
I am now getting this issue with tensordlow 2.15.x
