### ISSUE TITLE
feature request: remove control characters

### ISSUE THREAD

**Issue by AndreasMadsen** [tensorflow/text#817]
[Huggingface's BERT tokenizer](https://github.com/huggingface/transformers/blob/f778edb739a1ef2ff96b09cf6b9e80fa3824a6ba/src/transformers/models/bert/tokenization_bert_fast.py#L144) removes control characters from the input:

> clean_text (`bool`, *optional*, defaults to `True`):
>         Whether or not to clean the text before tokenization by removing any control characters and replacing all
>         whitespaces by the classic one.

Unfortunately, it does not appear that such option/function exists in `tensorflow_text`. This creates some compatibility issues:

```python
import tensorflow as tf
import tensorflow_text as tftx
from transformers import BertTokenizer

# extract from IMDB-reviews
x = 'It\'s the kind of movie that looks like it was a lot of fun to shoot\x97 TOO much fun'

huggingface_tokenizer = BertTokenizer.from_pretrained("bert-base-cased")
tensorflow_tokenizer = tftx.FastWordpieceTokenizer(
    [ huggingface_tokenizer.ids_to_tokens[i] for i in range(len(huggingface_tokenizer.vocab)) ],
    support_detokenization=True
)

print(tensorflow_tokenizer.detokenize(huggingface_tokenizer(x)['input_ids'][1:-1]))
print(tensorflow_tokenizer.detokenize(tensorflow_tokenizer.tokenize(x)))
```

outputs:

```
tf.Tensor(b"It ' s the kind of movie that looks like it was a lot of fun to shoot TOO much fun", shape=(), dtype=string)
tf.Tensor(b"It ' s the kind of movie that looks like it was a lot of fun to [UNK] TOO much fun", shape=(), dtype=string)
```

It would be great if such a function similar to `text.normalize_utf8` could be added for removing control characters.

**Comment by thuang513** [comment]
[`text.BertTokenizer`](https://www.tensorflow.org/text/api_docs/python/text/BertTokenizer) contains a `normalization_form` param that you can add which normalizes the inputs to the desired form using `text.normalize_utf8`.

**Comment by AndreasMadsen** [comment]
@thuang513 Yes, but `text.normalize_utf8` is about unicode normalization, not control character removal.

I did manage to do it with:
```
text = tf.strings.regex_replace(text, r'[\x{00ad}\x{0000}-\x{001f}\x{007f}-\x{009f}\x{E000}-\x{F8FF}]', r'')
```
