### ISSUE TITLE
Incompatibility between requested `tensorflow` and `tensorflow-macos` versions in 2.8 series

### ISSUE THREAD

**Issue by connorbrinton** [tensorflow/text#841]
The TensorFlow Text package requires use of a matching minor version of TensorFlow. When TensorFlow Text is packaged as a pip package, it enforces this requirement with the following dependency specifier in [setup.py](https://github.com/tensorflow/text/blob/b301a47bb46588ec0f599cbed5b3680d12435d88/oss_scripts/pip_package/setup.py#L76):
```python
        'tensorflow>=2.8.0, <2.9',
```

However, on the 2.8 branch, [there is another dependency specifier](https://github.com/tensorflow/text/blob/b301a47bb46588ec0f599cbed5b3680d12435d88/oss_scripts/pip_package/setup.py#L77) just below the one referenced above:
```python
        'tensorflow-macos>=2.7.0, <2.8.0; platform_machine == "arm64" and platform_system == "Darwin"',
```

This dependency specifier is intended for Apple Silicon systems, due to the fact that the `tensorflow` package doesn't support Apple Silicon devices. However, there are two problems with the above dependency specifiers:
1. On an Apple Silicon system, the main `tensorflow` package should not be installed.
2. The `tensorflow-macos` dependency minor version (currently 2.7.x) should match the TensorFlow Text minor version (2.8.x).

I believe that commit https://github.com/tensorflow/text/commit/a7e1b5b6cdc4d35eb2849f83eaa670bcc7faf10d accidentally caused both of these problems.

This typically isn't a problem for users installing TensorFlow Text using pip on non-Apple Silicon devices, since pip just tries to find the best set of packages for the current system. However, this is a problem for package managers like Poetry, which create a deterministic lock file allowing a similar set of dependencies to be installed across different systems, modulo any architectural differences. Since Poetry needs to resolve a combination of dependencies that will work for any system, it eagerly tries to identify a version of tensorflow-macos that will work on Apple Silicon devices. However, since the minor versions of the tensorflow and tensorflow-macos dependencies don't match, it's unable to find an appropriate version of keras that both can use. As a result, installing tensorflow-text (>=2.8.0) using Poetry is currently impossible.

I've opened [a PR to fix these issues](https://github.com/tensorflow/text/pull/838) by restoring qualifiers for the `tensorflow` dependency and bumping the minor version of the `tensorflow-macos` dependency specifier 🙂 

Thanks for maintaining TensorFlow Text! 😄

**Comment by sun1638650145** [comment]
Great! This is not the case on the master branch, not sure why this is happening on the release version.

**Comment by broken** [comment]
Thanks for pointing this out. Your PR has been merged. PRs require at least two reviews so they sometimes take time to work their way through.

With regard to the problematic commit: The version updates are automated, so it looks like that script needs to be updated to not clobber these requirements. And while the changes should be reviewed, it has been stable for so long I'm not surprised they weren't looked at closely. I'll make sure the script gets updated.

Thanks for the PR!
