### ISSUE TITLE
classify_text_with_bert does not ALWAYS use  GPU (Kaggle)

### ISSUE THREAD

**Issue by rbhambriiit** [tensorflow/text#847]
Hi,
I tried running the tutorial:
https://www.tensorflow.org/text/tutorials/classify_text_with_bert

over kaggle.
please take a look at my notebook: https://www.kaggle.com/rbhambri/bert-classifier-imdb-20newsgroup

**Comment by rbhambriiit** [comment]
Issue1:

I could not get it running by specifying the versions suggested.

! pip install  -U "tensorflow-text==2.8.*"
pip install -q tf-models-official==2.7.0
import tensorflow_text as text  # Registers the ops.

logs:

/opt/conda/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/api/_v1/estimator/__init__.py in <module>
      8 import sys as _sys
      9 
---> 10 from tensorflow_estimator.python.estimator.api._v1.estimator import experimental
     11 from tensorflow_estimator.python.estimator.api._v1.estimator import export
     12 from tensorflow_estimator.python.estimator.api._v1.estimator import inputs

/opt/conda/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/api/_v1/estimator/experimental/__init__.py in <module>
      8 import sys as _sys
      9 
---> 10 from tensorflow_estimator.python.estimator.canned.dnn import dnn_logit_fn_builder
     11 from tensorflow_estimator.python.estimator.canned.kmeans import KMeansClustering as KMeans
     12 from tensorflow_estimator.python.estimator.canned.linear import LinearSDCA

/opt/conda/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/canned/dnn.py in <module>
     26 from tensorflow.python.keras.engine import training
     27 from tensorflow.python.keras.layers import core as keras_core
---> 28 from tensorflow.python.keras.layers import normalization as keras_norm
     29 from tensorflow.python.keras.utils import losses_utils
     30 from tensorflow.python.util.tf_export import estimator_export

ImportError: cannot import name 'normalization' from 'tensorflow.python.keras.layers' (/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/layers/__init__.py)

**Comment by rbhambriiit** [comment]
![image](https://user-images.githubusercontent.com/13808100/155897473-59416c63-b457-4499-91a0-bc734d4f5d84.png)

**Comment by rbhambriiit** [comment]
Observations:

kernel is not able to use gpu.
trining time looks really crazy on cpu.

please suggest any changes which can help to run this practically.

Thanks!

**Comment by rbhambriiit** [comment]
Update:
i was able to resolve the gpu warning seen during  bert_preprocess_model = hub.KerasLayer(tfhub_handle_preprocess)

However, still this does not use gpu and really really slow

**Comment by broken** [comment]
do the other models fail to run on gpu too, or is bert_en_uncased the only one?

**Comment by rbhambriiit** [comment]
Update:
I tried to use the 'bert_en_cased' model and it could use the gpu as well.

So far only noticed the issue with the uncased version.

**Comment by rbhambriiit** [comment]
Update:
I used an older version of tensorflow-text library. 
! pip install  -U "tensorflow-text==2.6.*"

I could see the gpu in action for all models. You might want to check the latest version 2.8*
Else, feel free to close this issue.

Thanks!
