### ISSUE TITLE
add "step" and "drop_remainder" param to "sliding_window"

### ISSUE THREAD

**Issue by EternalMoment** [tensorflow/text#85]
Hey team,

For the current `sliding_window` function, would you consider add a `step` param, which indicates the number of steps moving forward for the next window?

The `drop_remainder' = True param will drop windows which have length less than width.

For example:
width=2, step=2, drop_remainder=False
[1,2,3,4,5]  => (1,2) (3,4) (5)

width=2, step=2, drop_remainder=True
[1,2,3,4,5]  => (1,2) (3,4) 

thanks!

**Comment by broken** [comment]
Yes. Would you want to submit a PR? Otherwise, if you had a good argument for why it would be needed, that would help prioritize it.
