### ISSUE TITLE
/text/tutorials/text_generation no longer works

### ISSUE THREAD

**Issue by MiloAkerman** [tensorflow/text#933]
I followed the ["Text Generation with an RNN"](https://www.tensorflow.org/text/tutorials/text_generation) tutorial verbatim and everything seems to work up until the "Export the Model" section, where the code shown saves the model but is unable to load it.

I believe this is due to missing function signatures but seeing as I was attempting to learn TensorFlow with this tutorial I am a bit stumped. Any help is appreciated in terms of how I would load the model and I suggest the page be updated

**Comment by broken** [comment]
I just ran the full tutorial from inside colab and didn't have any issues. There were a couple of warning messages, but they shouldn't affect results. These tutorial are also ran daily automatically to verify completeness without failure, and there haven't been any failures lately.

Can you be more specific about what you are seeing? Are you running inside of colab, or copying the code to be ran locally? What is the error?

**Comment by MiloAkerman** [comment]
Hello, I think the issue may be caused by me loading the model from a different file. What Tensorflow version are you running? I still had to make quite a few changes to get it to work on TF2

**Comment by broken** [comment]
it's the default version in colab at the moment which is 2.8.0
