### ISSUE TITLE
Can't build from source on M1

### ISSUE THREAD

**Issue by dlwh** [tensorflow/text#971]
Hi,

I'm on an M1 back. I've installed tensorflow-macos and would like to build this from scratch, which I think should be possible (as per #756). However, I'm getting issues building dependencies namely com_google_sentencepiece:

```
ERROR: /private/var/tmp/_bazel_dlwh/5b5343ed274731dd03bb9e218576ebef/external/com_google_sentencepiece/BUILD.bazel:51:11: Compiling src/model_interface.cc failed: (Exit 1): cc_wrapper.sh failed: error executing command external/local_config_cc/cc_wrapper.sh -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -Wunused-but-set-parameter -Wno-free-nonheap-object -fcolor-diagnostics ... (remaining 70 arguments skipped)
external/com_google_sentencepiece/src/model_interface.cc:20:10: error: module @com_google_sentencepiece//:sentencepiece_processor does not depend on a module exporting 'absl/strings/str_format.h'
#include "absl/strings/str_format.h"
```

Due to a race I sometimes get errors about not depending on darts_clone instead. I've tried master and v2.9.0

Am I doing something wrong?

**Comment by sun1638650145** [comment]
[Here](https://github.com/sun1638650145/Libraries-and-Extensions-for-TensorFlow-for-Apple-Silicon/releases/tag/v2.9) is my pre-compiled `whl` file, and you can check if yours is different from the [tutorial](https://github.com/sun1638650145/Libraries-and-Extensions-for-TensorFlow-for-Apple-Silicon/blob/main/tutorials/text/text.md). There has been a problem similar to yours, and you can discuss it [here](https://github.com/tensorflow/text/issues/823#issuecomment-1191182243).

**Comment by dlwh** [comment]
Ah yes, I'm running into that exact same issue. Thanks, I had somehow
missed it. We can close this as a duplicate. (I followed the tutorial
closely and it didn't change anything)

**Comment by xleviator** [comment]
Did anyone get this to work on a more recent tree or with Python 3.10? tensorflow_text-2.9.0-cp310-cp310-macosx_11_0_arm64.whl - I didn't try a recent tree with Python 3.9.

```
ImportError: dlopen(...python3.10/site-packages/tensorflow_text/core/pybinds/tflite_registrar.so, 0x0002): tried: '...lib/python3.10/site-packages/tensorflow_text/core/pybinds/tflite_registrar.so' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))
```

**Comment by vedmant** [comment]
I have the same issue: 
```
 from tensorflow_text.core.pybinds import tflite_registrar
ImportError: dlopen(/Users/vedmant/miniconda3/lib/python3.10/site-packages/tensorflow_text/core/pybinds/tflite_registrar.so, 0x0002): tried: '/Users/vedmant/miniconda3/lib/python3.10/site-packages/tensorflow_text/core/pybinds/tflite_registrar.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'))
```

Any clear way how to fix this?

**Comment by sun1638650145** [comment]
@xleviator @vedmant Please update `macOS` and `Xcode`, then you compile according to the [new tutorial](https://github.com/sun1638650145/Libraries-and-Extensions-for-TensorFlow-for-Apple-Silicon/blob/main/tutorials/text/text.md) or can use my pre-compiled [`tensorflow-text 2.12.0`](https://github.com/sun1638650145/Libraries-and-Extensions-for-TensorFlow-for-Apple-Silicon/releases/tag/v2.12). But I am not sure whether the new version of `Xcode` can solve the problem on `2.10.0` and `2.11.0`, further confirmation is needed.
